# Shared unit-name membership for the compiler and reference lexers.
#
# data/unit_names.txt is generated by scripts/gen_units.rb. Read it exactly
# once when this module is initialized; token scans only perform Hash lookups.

-> unit_names_registry_path
  root = env("TUNGSTEN_ROOT")
  if root != nil && root != ""
    rooted = root + "/data/unit_names.txt"
    if file?(rooted)
      return rooted
  if file?("data/unit_names.txt")
    return "data/unit_names.txt"
  nil

-> load_known_unit_names
  path = unit_names_registry_path()
  if path == nil
    raise "missing unit-name registry data/unit_names.txt; set TUNGSTEN_ROOT to the Tungsten install root"
  source = read_file(path)
  if source == nil
    raise "could not read unit-name registry " + path

  names = {}
  lines = source.split("\n")
  i = 0
  while i < lines.size()
    name = lines[i].strip()
    if name != ""
      names[name] = true
    i += 1
  names

# Top-level containers are initialized once per compiler process. Both lexer
# implementations share this immutable-after-load membership hash.
known_unit_names = load_known_unit_names()

-> known_unit_name?(s)
  known_unit_names.has_key?(s)

# Int exponent back to its source superscript: `m²` parses as POW(m, 2), so
# rejoining the spelling maps 2 → "²". Negative superscripts do not lex in
# bare expression position; quoted spellings cover them.
-> unit_superscript_for_power(v)
  if v == 1
    return "¹"
  if v == 2
    return "²"
  if v == 3
    return "³"
  if v == 4
    return "⁴"
  if v == 5
    return "⁵"
  if v == 6
    return "⁶"
  if v == 7
    return "⁷"
  if v == 8
    return "⁸"
  if v == 9
    return "⁹"
  nil
