require "tungsten/ast/node"

module Tungsten
  module AST
    autoload :KeywordArgs,     "tungsten/ast/keyword_args"
    autoload :KeywordValue,    "tungsten/ast/keyword_value"

    autoload :Arg,             "tungsten/ast/arg"
    autoload :And,             "tungsten/ast/and"
    autoload :Assign,          "tungsten/ast/assign"
    autoload :AssignOp,        "tungsten/ast/assign_op"
    autoload :BinaryOp,        "tungsten/ast/binary_op"
    autoload :Block,           "tungsten/ast/block"
    autoload :Call,            "tungsten/ast/call"
    autoload :List,            "tungsten/ast/list"
    autoload :Match,           "tungsten/ast/match"
    autoload :Not,             "tungsten/ast/not"
    autoload :Or,              "tungsten/ast/or"
    autoload :InTest,          "tungsten/ast/in_test"
    autoload :Path,            "tungsten/ast/path"
    autoload :Splat,           "tungsten/ast/splat"
    autoload :UnaryExpression, "tungsten/ast/unary_expression"
    autoload :UnaryOp,         "tungsten/ast/unary_op"
    autoload :Var,             "tungsten/ast/var"
    autoload :Value,           "tungsten/ast/value"

    autoload :ArrayLiteral,    "tungsten/ast/array_literal"
    autoload :ClassVar,        "tungsten/ast/class_var"
    autoload :GlobalVar,       "tungsten/ast/global_var"
    autoload :HashLiteral,     "tungsten/ast/hash_literal"
    autoload :InstanceVar,     "tungsten/ast/instance_var"
    autoload :Self,            "tungsten/ast/self"
    autoload :ByteArrayInterpolation, "tungsten/ast/byte_array_interpolation"
    autoload :StringInterpolation, "tungsten/ast/string_interpolation"
    autoload :Symbol,          "tungsten/ast/symbol"
    autoload :Tuple,           "tungsten/ast/tuple"

    autoload :Accessor,        "tungsten/ast/keywords/accessor"
    autoload :Alias,           "tungsten/ast/keywords/alias"
    autoload :Begin,           "tungsten/ast/keywords/begin"
    autoload :Break,           "tungsten/ast/keywords/break"
    autoload :Case,            "tungsten/ast/keywords/case"
    autoload :CaseExpr,        "tungsten/ast/keywords/case_expr"
    autoload :ClassDef,        "tungsten/ast/keywords/class_def"
    autoload :Def,             "tungsten/ast/keywords/def"
    autoload :Fn,              "tungsten/ast/keywords/fn"
    autoload :Flip2,           "tungsten/ast/keywords/flip2"
    autoload :Flip3,           "tungsten/ast/keywords/flip3"
    autoload :If,              "tungsten/ast/keywords/if"
    autoload :Is,              "tungsten/ast/keywords/is"
    autoload :ModuleDef,       "tungsten/ast/keywords/module_def"
    autoload :OnGuard,         "tungsten/ast/keywords/on_guard"
    autoload :Next,            "tungsten/ast/keywords/next"
    autoload :Print,           "tungsten/ast/keywords/print"
    autoload :Write,           "tungsten/ast/keywords/write"
    autoload :Raise,           "tungsten/ast/keywords/raise"
    autoload :Redo,            "tungsten/ast/keywords/redo"
    autoload :Retry,           "tungsten/ast/keywords/retry"
    autoload :Return,          "tungsten/ast/keywords/return"
    autoload :Super,           "tungsten/ast/keywords/super"
    autoload :TargetAnd,       "tungsten/ast/keywords/target_and"
    autoload :TargetDesignator, "tungsten/ast/keywords/target_designator"
    autoload :TargetNot,       "tungsten/ast/keywords/target_not"
    autoload :TargetOr,        "tungsten/ast/keywords/target_or"
    autoload :TraitDef,        "tungsten/ast/keywords/trait_def"
    autoload :While,           "tungsten/ast/keywords/while"
    autoload :Until,           "tungsten/ast/keywords/while"
    autoload :Use,             "tungsten/ast/keywords/use"
    autoload :With,            "tungsten/ast/keywords/with"
    autoload :Yield,           "tungsten/ast/keywords/yield"

    autoload :Boolean,         "tungsten/ast/literals/boolean"
    autoload :ByteArrayLiteral, "tungsten/ast/literals/byte_array_literal"
    autoload :Char,            "tungsten/ast/literals/char"
    autoload :CIDR4,           "tungsten/ast/literals/cidr4"
    autoload :CIDR6,           "tungsten/ast/literals/cidr6"
    autoload :Date,            "tungsten/ast/literals/date"
    autoload :DateTime,        "tungsten/ast/literals/date_time"
    autoload :Decimal,         "tungsten/ast/literals/decimal"
    autoload :Duration,        "tungsten/ast/literals/duration"
    autoload :FalseLiteral,    "tungsten/ast/literals/false_literal"
    autoload :Float,           "tungsten/ast/literals/float"
    autoload :Int,             "tungsten/ast/literals/int"
    autoload :MagicConstant,   "tungsten/ast/literals/magic_constant"
    autoload :Month,           "tungsten/ast/literals/month"
    autoload :IP4,             "tungsten/ast/literals/ip4"
    autoload :KeyLiteral,      "tungsten/ast/literals/key_literal"
    autoload :IP6,             "tungsten/ast/literals/ip6"
    autoload :Nil,             "tungsten/ast/literals/nil"
    autoload :RangeLiteral,    "tungsten/ast/literals/range_literal"
    autoload :RegexLiteral,    "tungsten/ast/literals/regex_literal"
    autoload :StringLiteral,   "tungsten/ast/literals/string_literal"
    autoload :TimeLiteral,     "tungsten/ast/literals/time_literal"
    autoload :SetLiteral,      "tungsten/ast/literals/set_literal"
    autoload :MultisetLiteral, "tungsten/ast/literals/set_literal"
    autoload :TypedArray,      "tungsten/ast/literals/typed_array"
    autoload :TrueLiteral,     "tungsten/ast/literals/true_literal"
    autoload :UUID,            "tungsten/ast/literals/uuid"
    autoload :Week,            "tungsten/ast/literals/week"
    autoload :WValue,          "tungsten/ast/literals/w_value"
    autoload :ColorLiteral,      "tungsten/ast/literals/color_literal"
    autoload :CurrencyLiteral,   "tungsten/ast/literals/currency_literal"
    autoload :RationalLiteral,   "tungsten/ast/literals/rational"
    autoload :PercentageLiteral, "tungsten/ast/literals/percentage_literal"
    autoload :QuantityLiteral,   "tungsten/ast/literals/quantity_literal"
    autoload :MeasurementLiteral, "tungsten/ast/literals/measurement_literal"
  end
end
