# Strings: common methods (case, search, slice, pad, split/join, translate).
#
# Cross-engine parity spec (scripts/parity.sh).

<< "concat [("hel" + "lo")]"
<< "repeat [("ab" * 3)]"
<< "size [("hello").size]"
<< "length [("hello").length]"
<< "idx [("abcdef")[2]]"
<< "idx.neg [("abcdef")[-1]]"
<< "slice [("abcdef").slice(1, 3)]"
<< "upcase [("hello").upcase]"
<< "downcase [("HeLLo").downcase]"
<< "capitalize [("hello").capitalize]"
<< "swapcase [("HeLLo").swapcase]"
<< "reverse [("hello").reverse]"
<< "split [("a,b,c").split(",").size] [("a,b,c").split(",").join("|")]"
<< "join [["a", "b", "c"].join("-")]"
<< "include [("hello").include?("ell")]"
<< "starts [("hello").starts_with?("he")]"
<< "ends [("hello").ends_with?("lo")]"
<< "strip [("  hi  ").strip]|"
<< "replace [("hello").replace("l", "L")]"
<< "gsub [("hello").gsub("l", "L")]"
<< "index [("hello").index("l")]"
<< "chars [("abc").chars.join("|")]"
<< "to_i [("42").to_i]"
<< "to_f [("2.5").to_f]"
<< "cmp [("abc" < "abd")]"
<< "eq [("abc" == "abc")]"
<< "empty [("").empty?]"
<< "chr [(65).chr]"
<< "ord [("A").ord]"
<< "lines [("a\nb\nc").lines.size]"
<< "tr [("hello").tr("l", "r")]"
<< "delete [("hello").delete("l")]"
<< "squeeze [("aaabbb").squeeze]"
<< "fmt [("%s-%s" % ["a", "b"])]"
