# DecisionTreeExport specs — deterministic standalone Tungsten source for a
# fitted DecisionTreeClassifier.
#
# Run from the repo root (both engines, exit 0 = green):
#   bin/tungsten bits/tungsten-koala/spec/decision_tree_export_spec.w
#   bin/tungsten -o /tmp/koala_tree_export_spec bits/tungsten-koala/spec/decision_tree_export_spec.w
#   /tmp/koala_tree_export_spec

use spec
use koala
use support

# This is the exact source expected from the XOR export below. Keeping a
# source-level copy in the spec makes both engines compile and execute the
# generated shape; the exact-string assertion ties it to the exporter.
-> koala_export_fixture_schema_version
  1

-> koala_export_fixture_schema_checksum
  2065074467

-> koala_export_fixture_feature_count
  2

-> koala_export_fixture(features, feature_schema_checksum)
  raise "koala_export_fixture: feature schema checksum mismatch" if feature_schema_checksum != 2065074467
  raise "koala_export_fixture: expected 2 features" if features.size != 2
  if features[0].to_f <= ~0.5
    if features[1].to_f <= ~0.5
      0
    else
      1
  else
    if features[1].to_f <= ~0.5
      1
    else
      0

# A second compiled copy exercises the round-trip f64 spellings rather than
# only binary-exact halves and Integer arm ids.
-> koala_export_float_fixture(features, feature_schema_checksum)
  raise "koala_export_float_fixture: feature schema checksum mismatch" if feature_schema_checksum != 1967699392
  raise "koala_export_float_fixture: expected 1 feature" if features.size != 1
  if features[0].to_f <= ~0.73809523809523803
    ~0.33333333333333331
  else
    ~0.14285714285714285

describe "DecisionTreeExport standalone Tungsten source" ->
  it "emits deterministic nested source whose compiled predictions match the fitted tree" ->
    x = [[0, 0], [0, 1], [1, 0], [1, 1]]
    y = [0, 1, 1, 0]
    model = DecisionTreeClassifier.new
    model.fit(x, y)

    artifact = DecisionTreeExport.export(model, [:x0, :x1], :koala_export_fixture)
    again = DecisionTreeExport.export(model, ["x0", "x1"], "koala_export_fixture")
    expect(artifact != nil).to be_true
    expect(artifact[:format]).to eq("koala-decision-tree-source")
    expect(artifact[:schema_version]).to eq(1)
    expect(artifact[:schema_checksum]).to eq(2065074467)
    expect(artifact[:feature_names]).to eq(["x0", "x1"])
    expect(artifact[:function_name]).to eq("koala_export_fixture")
    expect(artifact[:source]).to eq(again[:source])

    expected = [
      "# Generated by Koala DecisionTreeExport; do not edit.",
      "# schema-version: 1",
      "# schema-checksum: 2065074467",
      "# feature-order: 0=x0, 1=x1",
      "",
      "-> koala_export_fixture_schema_version",
      "  1",
      "",
      "-> koala_export_fixture_schema_checksum",
      "  2065074467",
      "",
      "-> koala_export_fixture_feature_count",
      "  2",
      "",
      "-> koala_export_fixture(features, feature_schema_checksum)",
      "  raise \"koala_export_fixture: feature schema checksum mismatch\" if feature_schema_checksum != 2065074467",
      "  raise \"koala_export_fixture: expected 2 features\" if features.size != 2",
      "  if features\[0\].to_f <= ~0.5",
      "    if features\[1\].to_f <= ~0.5",
      "      0",
      "    else",
      "      1",
      "  else",
      "    if features\[1\].to_f <= ~0.5",
      "      1",
      "    else",
      "      0",
      ""
    ].join("\n")
    expect(artifact[:source]).to eq(expected)
    expect(DecisionTreeExport.source(model, [:x0, :x1], :koala_export_fixture)).to eq(expected)

    exported_predictions = []
    x.each -> (row)
      exported_predictions.push(koala_export_fixture(row, artifact[:schema_checksum]))
    expect(exported_predictions.to_s).to eq(model.predict(x).to_s)
    expect(koala_export_fixture_schema_version).to eq(artifact[:schema_version])
    expect(koala_export_fixture_feature_count).to eq(artifact[:feature_names].size)

  it "requires the caller to present the feature schema checksum and exact width" ->
    expect(-> () koala_export_fixture([0, 0], 2065074466)).to raise_error
    expect(-> () koala_export_fixture([0], 2065074467)).to raise_error
    expect(-> () koala_export_fixture([0, 0, 0], 2065074467)).to raise_error

  it "changes the schema checksum when ordered feature names drift" ->
    model = DecisionTreeClassifier.new
    model.fit([[0, 0], [1, 1]], [0, 1])
    original = DecisionTreeExport.export(model, [:variables, :clauses], :select_arm)
    reordered = DecisionTreeExport.export(model, [:clauses, :variables], :select_arm)
    renamed = DecisionTreeExport.export(model, [:variables, :literal_count], :select_arm)
    expect(original != nil).to be_true
    expect(reordered != nil).to be_true
    expect(renamed != nil).to be_true
    expect(original[:schema_checksum] != reordered[:schema_checksum]).to be_true
    expect(original[:schema_checksum] != renamed[:schema_checksum]).to be_true
    expect(original[:source] != reordered[:source]).to be_true
    expect(original[:source].include?("# feature-order: 0=variables, 1=clauses")).to be_true
    expect(reordered[:source].include?("# feature-order: 0=clauses, 1=variables")).to be_true

  it "validates model fit, ordered names, uniqueness, width, and function name" ->
    unfitted = DecisionTreeClassifier.new
    expect(DecisionTreeExport.export(unfitted, [:x])).to be_nil

    model = DecisionTreeClassifier.new
    model.fit([[0, 0], [1, 1]], [0, 1])
    expect(DecisionTreeExport.export(model, nil)).to be_nil
    expect(DecisionTreeExport.export(model, "x0,x1")).to be_nil
    expect(DecisionTreeExport.export(model, [:x])).to be_nil
    expect(DecisionTreeExport.export(model, [:x, :x])).to be_nil
    expect(DecisionTreeExport.export(model, [:x, "bad-name"])).to be_nil
    expect(DecisionTreeExport.export(model, [:x, ""])).to be_nil
    expect(DecisionTreeExport.export(model, [:x, 7])).to be_nil
    expect(DecisionTreeExport.export(model, [:x0, :x1], :BadName)).to be_nil
    expect(DecisionTreeExport.export(model, [:x0, :x1], "bad-name")).to be_nil
    expect(DecisionTreeExport.export(model, [:x0, :x1], "if")).to be_nil
    expect(DecisionTreeExport.export(model, [:x0, :x1], 7)).to be_nil

    defaulted = DecisionTreeExport.export(model, [:x0, :x1])
    expect(defaulted[:function_name]).to eq("koala_tree_predict")
    expect(defaulted[:source].include?("-> koala_tree_predict(features, feature_schema_checksum)")).to be_true

  it "emits round-trip f64 literals and refuses nonnumeric or nonfinite predictions" ->
    third = 1.to_f / 3.to_f
    seventh = 1.to_f / 7.to_f
    expect(DecisionTreeExport.float_literal(6.to_f)).to eq("~6.0")
    expect(DecisionTreeExport.float_literal(third)).to eq("~0.33333333333333331")
    expect(DecisionTreeExport.float_literal(seventh).slice(0, 1)).to eq("~")
    expect(DecisionTreeExport.float_literal(seventh).slice(1, 64).to_f == seventh).to be_true

    numeric = DecisionTreeClassifier.new
    numeric.fit([[third], [seventh + 1.to_f]], [third, seventh])
    artifact = DecisionTreeExport.export(numeric, [:ratio], :numeric_tree)
    expect(artifact != nil).to be_true
    threshold_literal = DecisionTreeExport.float_literal(numeric.tree[:threshold])
    expect(artifact[:source].include?("features\[0\].to_f <= " + threshold_literal)).to be_true
    expect(artifact[:source].include?(DecisionTreeExport.float_literal(third))).to be_true
    expect(artifact[:source].include?(DecisionTreeExport.float_literal(seventh))).to be_true
    compiled_predictions = [
      koala_export_float_fixture([third], 1967699392),
      koala_export_float_fixture([seventh + 1.to_f], 1967699392)
    ]
    expect(compiled_predictions.to_s).to eq(numeric.predict([[third], [seventh + 1.to_f]]).to_s)

    symbolic = DecisionTreeClassifier.new
    symbolic.fit([[0], [1]], [:left, :right])
    expect(DecisionTreeExport.export(symbolic, [:x], :symbolic_tree)).to be_nil

    infinity = 1.to_f
    1100.times -> (i)
      infinity *= 2.to_f
    expect(DecisionTreeExport.prediction_literal(infinity)).to be_nil
    expect(DecisionTreeExport.prediction_literal(infinity - infinity)).to be_nil
    numeric.tree[:threshold] = infinity
    expect(DecisionTreeExport.export(numeric, [:ratio], :nonfinite_tree)).to be_nil
