# Random forest specs — RandomForestClassifier / RandomForestRegressor and
# the DecisionTree.split_features hook they stand on, on the
# tungsten-spec framework.
#
# Run from the repo root (both engines, exit 0 = green):
#   bin/tungsten bits/tungsten-koala/spec/random_forest_spec.w
#   bin/tungsten -o /tmp/rf_spec bits/tungsten-koala/spec/random_forest_spec.w && /tmp/rf_spec
#
# THREE PROPERTIES carry the file, and everything else supports them.
#
#   1. THE PLUMBING IS PINNED TO A SINGLE TREE. Switch off both sources of
#      randomness — `bootstrap = false`, `max_features = :all` — and grow
#      ONE tree, and the result must not merely resemble a
#      DecisionTreeClassifier: it must be the same tree, asserted against
#      the RENDERED tree, node for node. If bagging, per-split subsampling
#      or the averaging were wired wrong, turning them off could not land
#      back on the tree they were built from.
#
#   2. THE ENSEMBLE ACTUALLY BUYS SOMETHING. On a problem built to punish a
#      single tree — two informative features, junk features beside them,
#      and a quarter of the TRAINING labels flipped, scored against a CLEAN
#      test set — a deep tree memorizes the flipped rows and a forest
#      averages them away. Both forests are asserted to beat their own
#      single-tree counterpart there, and to hold their own on clean data.
#
#   3. IT IS DETERMINISTIC. Same seed twice is not "similar": it is a
#      byte-identical Persist payload, which pins every threshold in every
#      tree, on both engines.
#
# Datasets are generated by the SAME MINSTD stream the library seeds with,
# so the fixtures are exact integers on both engines and no float literal
# is needed to build them. Sizes are deliberately small — the interpreter
# walks every node of every tree — and the two expensive forests are each
# fitted in exactly ONE example.
#
# Predictions are compared via `join`, never `to_s`: compiled Array `==` is
# identity. Floats are compared by inequality or against a tolerance
# derived with .to_f, never by their decimal text.

use spec
use koala

# --- Fixtures --------------------------------------------------------

+ Fx
  # One step of the library's MINSTD stream, so the fixtures are generated
  # by exactly the arithmetic the forest seeds itself with.
  -> .step(s)
    (s * 48271) % 2147483647

  # A classification problem with `nf` integer features in 0..19, of which
  # only the first two matter: the label is "a" when x0 + x1 >= 20 and "b"
  # otherwise, which splits roughly evenly. `noise` is the PERCENT of
  # labels flipped — 0 for a clean set (the test data), 25 for the
  # training set a lone tree will memorize.
  -> .clf(n, seed, noise, nf)
    s = seed % 2147483647
    s = 1 if s <= 0
    rows = []
    labels = []
    i = 0
    while i < n
      r = []
      c = 0
      while c < nf
        s = Fx.step(s)
        r.push(s % 20)
        c += 1
      lab = "b"
      lab = "a" if r[0] + r[1] >= 20
      if noise > 0
        s = Fx.step(s)
        if s % 100 < noise
          flip = "a"
          flip = "b" if lab == "a"
          lab = flip
      rows.push(r)
      labels.push(lab)
      i += 1
    { rows: rows, labels: labels }

  # The regression twin: y = 3*x0 - 2*x1, plus junk columns, plus additive
  # integer noise uniform on -noise..+noise.
  -> .reg(n, seed, noise, nf)
    s = seed % 2147483647
    s = 1 if s <= 0
    rows = []
    ys = []
    i = 0
    while i < n
      r = []
      c = 0
      while c < nf
        s = Fx.step(s)
        r.push(s % 20)
        c += 1
      v = 3 * r[0] - 2 * r[1]
      if noise > 0
        s = Fx.step(s)
        v = v + (s % (2 * noise + 1)) - noise
      rows.push(r)
      ys.push(v)
      i += 1
    { rows: rows, ys: ys }

  # A PERFECTLY SEPARABLE problem: one threshold on x0 decides the label,
  # and the remaining columns are junk. A single stump is already the
  # optimal classifier here, which is exactly what makes it the fair test
  # of whether bagging COSTS anything on clean data.
  -> .separable(n, seed, nf)
    s = seed % 2147483647
    s = 1 if s <= 0
    rows = []
    labels = []
    i = 0
    while i < n
      r = []
      c = 0
      while c < nf
        s = Fx.step(s)
        r.push(s % 20)
        c += 1
      lab = "b"
      lab = "a" if r[0] >= 10
      rows.push(r)
      labels.push(lab)
      i += 1
    { rows: rows, labels: labels }

  # A small CLEAN set for the cheap structural examples.
  -> .small
    Fx.clf(24, 5, 0, 3)

  -> .small_reg
    Fx.reg(24, 5, 0, 3)

  # A tolerance for "these floats agree": one part in a million, derived
  # rather than written as a literal.
  -> .eps
    1.to_f / 1000000.to_f

  -> .close?(a, b)
    d = a - b
    d = 0.to_f - d if d < 0.to_f
    d < Fx.eps

  # A model dumped and loaded back, in one step.
  -> .cycle(model)
    Persist.loads(Persist.dumps(model))

  # Predictions as one comparable string.
  -> .preds(model, rows)
    out = nil
    p = model.predict(rows)
    out = p.join(",") if p != nil
    out

# --- The additive hook in lib/decision_tree.w ------------------------

describe "DecisionTree.split_features" ->
  it "scans every feature, ascending, when no budget is set" ->
    cfg = { nf: 5, rng: 7 }
    expect(DecisionTree.split_features(cfg).join(",")).to eq("0,1,2,3,4")
    # ... and consumes no randomness doing it, so an ordinary tree is the
    # pure function of its data it always was.
    expect(cfg[:rng]).to eq(7)

  it "treats a nil budget, and a budget wider than the data, as all of them" ->
    expect(DecisionTree.split_features({ nf: 4, max_features: nil, rng: 1 }).join(",")).to eq("0,1,2,3")
    expect(DecisionTree.split_features({ nf: 4, max_features: 9, rng: 1 }).join(",")).to eq("0,1,2,3")

  it "draws a sorted subset of the asked-for size and advances the stream" ->
    cfg = { nf: 6, max_features: 3, rng: 12345 }
    picked = DecisionTree.split_features(cfg)
    expect(picked.size).to eq(3)
    expect(cfg[:rng] == 12345).to be_false
    # Ascending, distinct, and inside range — so the tie-break rule the
    # tree documents (lowest feature index wins) survives subsampling.
    ordered = true
    prev = -1
    picked.each -> (j)
      ordered = false if j <= prev || j < 0 || j >= 6
      prev = j
    expect(ordered).to be_true

  it "redraws per call, so successive nodes see different features" ->
    cfg = { nf: 8, max_features: 2, rng: 99 }
    seen = []
    12.times -> (c)
      seen.push(DecisionTree.split_features(cfg).join("-"))
    distinct = []
    seen.each -> (v)
      distinct.push(v) if !distinct.include?(v)
    expect(distinct.size > 1).to be_true

  it "is a pure function of the state it is handed" ->
    one = DecisionTree.split_features({ nf: 7, max_features: 3, rng: 4242 })
    two = DecisionTree.split_features({ nf: 7, max_features: 3, rng: 4242 })
    expect(one.join(",")).to eq(two.join(","))

  it "sorts integers as integers, so the result can index a row" ->
    expect(DecisionTree.sorted_ints([3, 1, 2, 1, 0]).join(",")).to eq("0,1,1,2,3")
    expect(DecisionTree.sorted_ints([]).join(",")).to eq("")

# --- The seeded machinery -------------------------------------------

describe "RandomForest machinery" ->
  it "steps the same MINSTD stream Splitter and KFold use" ->
    expect(RandomForest.step(1)).to eq(48271)
    expect(RandomForest.step(48271)).to eq((48271 * 48271) % 2147483647)

  it "normalizes any seed, including nil, into a usable state" ->
    expect(RandomForest.seed_state(nil)).to eq(1)
    expect(RandomForest.seed_state(0)).to eq(1)
    expect(RandomForest.seed_state(42)).to eq(42)
    expect(RandomForest.seed_state(2147483647)).to eq(1)

  it "computes floor(sqrt) and floor(log2) without touching a float" ->
    expect(RandomForest.isqrt(1)).to eq(1)
    expect(RandomForest.isqrt(4)).to eq(2)
    expect(RandomForest.isqrt(10)).to eq(3)
    expect(RandomForest.isqrt(16)).to eq(4)
    expect(RandomForest.ilog2(1)).to eq(0)
    expect(RandomForest.ilog2(8)).to eq(3)
    expect(RandomForest.ilog2(9)).to eq(3)

  it "resolves every documented max_features setting to a count" ->
    expect(RandomForest.feature_count(:all, 9, false)).to eq(9)
    expect(RandomForest.feature_count(:sqrt, 9, false)).to eq(3)
    expect(RandomForest.feature_count(:log2, 9, false)).to eq(3)
    expect(RandomForest.feature_count(4, 9, false)).to eq(4)
    # An integer is clamped into 1..n_features rather than refused.
    expect(RandomForest.feature_count(99, 9, false)).to eq(9)
    expect(RandomForest.feature_count(0, 9, false)).to eq(1)
    # :log2 of a single feature would be 0 — a split search needs one.
    expect(RandomForest.feature_count(:log2, 1, false)).to eq(1)

  it "defaults to sqrt for classification and to everything for regression" ->
    expect(RandomForest.feature_count(nil, 9, false)).to eq(3)
    expect(RandomForest.feature_count(nil, 9, true)).to eq(9)

  it "refuses a max_features setting it does not know, rather than guessing" ->
    expect(RandomForest.feature_count(:bogus, 9, false)).to eq(-1)
    expect(RandomForest.feature_count("mostly", 9, true)).to eq(-1)

  it "draws a bootstrap of exactly n, leaving some rows out" ->
    counts = RandomForest.draw_counts(40, 12345)
    total = 0
    zeros = 0
    counts.each -> (c)
      total += c
      zeros += 1 if c == 0
    expect(counts.size).to eq(40)
    expect(total).to eq(40)
    # ~37% of rows are expected out of bag; the assertion is only that the
    # resample is genuinely WITH replacement, not a permutation.
    expect(zeros > 0).to be_true

  it "breaks an argmax tie to the lowest index, as the trees do" ->
    expect(RandomForest.argmax([1.to_f, 1.to_f, 1.to_f])).to eq(0)
    expect(RandomForest.argmax([1.to_f, 2.to_f, 2.to_f])).to eq(1)
    expect(RandomForest.argmax([3.to_f, 2.to_f, 1.to_f])).to eq(0)

# --- Property 1: the plumbing, pinned to a single tree ---------------

describe "a forest of one tree, with the randomness switched off" ->
  it "is the DecisionTreeClassifier it was built from, node for node" ->
    data = Fx.clf(64, 11, 0, 4)
    tree = DecisionTreeClassifier.new
    tree.fit(data[:rows], data[:labels])
    forest = RandomForestClassifier.new(1, :all, nil, 1, 0, nil, false)
    forest.fit(data[:rows], data[:labels])
    expect(forest.tree_count).to eq(1)
    # The RENDERED tree, not merely the predictions: same features, same
    # thresholds, same leaves, same order.
    expect(DecisionTree.render(forest.trees[0], "", []).join("\n")).to eq(tree.tree_lines.join("\n"))
    expect(Fx.preds(forest, data[:rows])).to eq(Fx.preds(tree, data[:rows]))
    # ... and the vote of a one-tree ensemble is that tree's own leaf
    # distribution, unchanged.
    fp = forest.predict_proba(data[:rows])
    tp = tree.predict_proba(data[:rows])
    same = true
    i = 0
    fp.each -> (row)
      j = 0
      row.each -> (v)
        same = false if !Fx.close?(v, tp[i][j])
        j += 1
      i += 1
    expect(same).to be_true

  it "is the DecisionTreeRegressor it was built from, node for node" ->
    data = Fx.reg(64, 13, 0, 4)
    tree = DecisionTreeRegressor.new
    tree.fit(data[:rows], data[:ys])
    forest = RandomForestRegressor.new(1, :all, nil, 1, 0, nil, false)
    forest.fit(data[:rows], data[:ys])
    expect(DecisionTree.render(forest.trees[0], "", []).join("\n")).to eq(tree.tree_lines.join("\n"))
    expect(Fx.preds(forest, data[:rows])).to eq(Fx.preds(tree, data[:rows]))

  it "honours max_depth and min_samples_leaf exactly as the tree does" ->
    data = Fx.clf(64, 11, 0, 4)
    tree = DecisionTreeClassifier.new(2, nil, 3)
    tree.fit(data[:rows], data[:labels])
    forest = RandomForestClassifier.new(1, :all, 2, 3, 0, nil, false)
    forest.fit(data[:rows], data[:labels])
    expect(DecisionTree.render(forest.trees[0], "", []).join("\n")).to eq(tree.tree_lines.join("\n"))

  it "has no out-of-bag score, because nothing was left out" ->
    data = Fx.small
    forest = RandomForestClassifier.new(4, :all, nil, 1, 1, nil, false)
    forest.fit(data[:rows], data[:labels])
    expect(forest.fitted?).to be_true
    expect(forest.oob_score).to be_nil

# --- Property 3: determinism ----------------------------------------

describe "RandomForest determinism" ->
  it "gives a byte-identical forest for the same seed" ->
    data = Fx.small
    one = RandomForestClassifier.new(8, :sqrt, nil, 1, 7)
    one.fit(data[:rows], data[:labels])
    two = RandomForestClassifier.new(8, :sqrt, nil, 1, 7)
    two.fit(data[:rows], data[:labels])
    expect(Fx.preds(one, data[:rows])).to eq(Fx.preds(two, data[:rows]))
    # The payload pins every threshold of every tree, not just the answers.
    expect(Persist.dumps(one)).to eq(Persist.dumps(two))

  it "gives a DIFFERENT forest for a different seed, and still fits" ->
    data = Fx.small
    one = RandomForestClassifier.new(8, :sqrt, nil, 1, 7)
    one.fit(data[:rows], data[:labels])
    other = RandomForestClassifier.new(8, :sqrt, nil, 1, 8)
    other.fit(data[:rows], data[:labels])
    expect(other.fitted?).to be_true
    expect(other.tree_count).to eq(8)
    expect(Persist.dumps(one) == Persist.dumps(other)).to be_false

  it "is reproducible with no seed at all — nil is a stream, not entropy" ->
    data = Fx.small
    one = RandomForestClassifier.new(6, :sqrt)
    one.fit(data[:rows], data[:labels])
    two = RandomForestClassifier.new(6, :sqrt)
    two.fit(data[:rows], data[:labels])
    expect(Persist.dumps(one)).to eq(Persist.dumps(two))
    # ... and that default stream is seed 1's.
    named = RandomForestClassifier.new(6, :sqrt, nil, 1, 1)
    named.fit(data[:rows], data[:labels])
    expect(Fx.preds(named, data[:rows])).to eq(Fx.preds(one, data[:rows]))

  it "refitting the same model twice lands in the same place" ->
    data = Fx.small
    model = RandomForestClassifier.new(6, :sqrt, nil, 1, 3)
    model.fit(data[:rows], data[:labels])
    first = Persist.dumps(model)
    model.fit(data[:rows], data[:labels])
    expect(Persist.dumps(model)).to eq(first)

  it "is deterministic for the regressor too" ->
    data = Fx.small_reg
    one = RandomForestRegressor.new(8, :sqrt, nil, 1, 21)
    one.fit(data[:rows], data[:ys])
    two = RandomForestRegressor.new(8, :sqrt, nil, 1, 21)
    two.fit(data[:rows], data[:ys])
    expect(Persist.dumps(one)).to eq(Persist.dumps(two))

# --- Property 2: the ensemble buys something ------------------------

describe "RandomForestClassifier against a lone deep tree" ->
  it "beats it on noisy training data, scored on clean test data" ->
    # A quarter of the TRAINING labels are flipped; the test labels are
    # not. An unlimited-depth tree will carve a box around each flipped
    # row and carry that damage to unseen data; the forest votes it down.
    train = Fx.clf(64, 7, 25, 4)
    test = Fx.clf(40, 999, 0, 4)
    deep = DecisionTreeClassifier.new
    deep.fit(train[:rows], train[:labels])
    tree_score = deep.score(test[:rows], test[:labels])
    forest = RandomForestClassifier.new(21, :sqrt, nil, 1, 42)
    forest.fit(train[:rows], train[:labels])
    forest_score = forest.score(test[:rows], test[:labels])
    expect(forest_score > tree_score).to be_true
    # Not a hair's breadth — the whole point is that averaging removes a
    # visible chunk of the variance.
    expect(forest_score - tree_score > Fx.eps * 10000.to_f).to be_true
    # The out-of-bag estimate is available with no held-out split at all,
    # and it is an estimate of accuracy on the NOISY distribution it was
    # trained on, so it sits below the clean-test number rather than
    # matching it.
    expect(forest.oob_score > 0.to_f).to be_true
    expect(forest.oob_score < 1.to_f).to be_true

  it "at least matches a single tree on clean, separable data" ->
    # Nothing to average away here: one threshold on x0 is already the
    # optimal rule, so a lone tree cannot be improved on. The claim is that
    # bagging does not COST anything — both reach the ceiling.
    train = Fx.separable(48, 3, 3)
    test = Fx.separable(32, 77, 3)
    deep = DecisionTreeClassifier.new
    deep.fit(train[:rows], train[:labels])
    forest = RandomForestClassifier.new(15, :all, nil, 1, 9)
    forest.fit(train[:rows], train[:labels])
    tree_score = deep.score(test[:rows], test[:labels])
    forest_score = forest.score(test[:rows], test[:labels])
    expect(Fx.close?(tree_score, 1.to_f)).to be_true
    expect(Fx.close?(forest_score, 1.to_f)).to be_true
    expect(forest_score >= tree_score).to be_true

describe "RandomForestRegressor against a lone deep tree" ->
  it "beats it on noisy training data, scored on clean test data" ->
    train = Fx.reg(64, 3, 25, 6)
    test = Fx.reg(40, 555, 0, 6)
    deep = DecisionTreeRegressor.new
    deep.fit(train[:rows], train[:ys])
    tree_r2 = deep.score(test[:rows], test[:ys])
    forest = RandomForestRegressor.new(21, nil, nil, 1, 42)
    forest.fit(train[:rows], train[:ys])
    forest_r2 = forest.score(test[:rows], test[:ys])
    expect(forest_r2 > tree_r2).to be_true
    expect(forest_r2 - tree_r2 > Fx.eps * 10000.to_f).to be_true
    expect(forest.oob_score).not_to be_nil

# --- The classifier's surface ---------------------------------------

describe "RandomForestClassifier" ->
  it "fits, predicts a label per row and scores an accuracy" ->
    data = Fx.small
    model = RandomForestClassifier.new(9, :sqrt, nil, 1, 4)
    expect(model.fitted?).to be_false
    expect(model.fit(data[:rows], data[:labels])).not_to be_nil
    expect(model.fitted?).to be_true
    expect(model.tree_count).to eq(9)
    expect(model.n_features).to eq(3)
    expect(model.classes.size).to eq(2)
    preds = model.predict(data[:rows])
    expect(preds.size).to eq(data[:rows].size)
    known = true
    preds.each -> (p)
      known = false if !model.classes.include?(p)
    expect(known).to be_true
    acc = model.score(data[:rows], data[:labels])
    expect(acc > 0.to_f).to be_true
    expect(acc <= 1.to_f).to be_true

  it "averages the trees' leaf distributions into a proper probability" ->
    data = Fx.small
    model = RandomForestClassifier.new(9, :sqrt, nil, 1, 4)
    model.fit(data[:rows], data[:labels])
    probs = model.predict_proba(data[:rows])
    expect(probs.size).to eq(data[:rows].size)
    expect(probs[0].size).to eq(model.classes.size)
    sums_to_one = true
    probs.each -> (row)
      total = 0.to_f
      row.each -> (v)
        total += v
      sums_to_one = false if !Fx.close?(total, 1.to_f)
    expect(sums_to_one).to be_true

  it "hands back a flat P(label) column for ROC, and nil for an unseen label" ->
    data = Fx.small
    model = RandomForestClassifier.new(9, :sqrt, nil, 1, 4)
    model.fit(data[:rows], data[:labels])
    col = model.predict_proba(data[:rows], model.classes[0])
    expect(col.size).to eq(data[:rows].size)
    # The column is the matching entry of the full distribution.
    full = model.predict_proba(data[:rows])
    expect(Fx.close?(col[0], full[0][0])).to be_true
    expect(model.predict_proba(data[:rows], "never-seen")).to be_nil

  it "reports an out-of-bag accuracy, the holdout the bootstrap paid for" ->
    data = Fx.small
    model = RandomForestClassifier.new(12, :sqrt, nil, 1, 6)
    model.fit(data[:rows], data[:labels])
    expect(model.oob_score).not_to be_nil
    expect(model.oob_score >= 0.to_f).to be_true
    expect(model.oob_score <= 1.to_f).to be_true

  it "answers the whole Estimable / SupervisedEstimator contract" ->
    model = RandomForestClassifier.new
    expect(model.estimator_name).to eq("RandomForestClassifier")
    expect(model.supervised?).to be_true
    expect(model.supports_sample_weight?).to be_true
    expect(model.respond_to?("fitted?")).to be_true
    expect(model.respond_to?("predict")).to be_true
    expect(model.respond_to?("params")).to be_true
    expect(model.respond_to?("with_params")).to be_true
    expect(model.respond_to?("to_state")).to be_true
    expect(model.respond_to?("persist_name")).to be_true

  it "defaults to ten gini trees, bootstrapped" ->
    p = RandomForestClassifier.new.params
    expect(p[:n_estimators]).to eq(10)
    expect(p[:max_features]).to be_nil
    expect(p[:max_depth]).to be_nil
    expect(p[:min_samples_leaf]).to eq(1)
    expect(p[:seed]).to be_nil
    expect(p[:criterion].to_s).to eq("gini")
    expect(p[:bootstrap]).to be_true

  it "round-trips every hyperparameter through with_params" ->
    model = RandomForestClassifier.new(7, :log2, 3, 2, 9, :entropy, false)
    again = model.with_params(model.params)
    p = again.params
    expect(p[:n_estimators]).to eq(7)
    expect(p[:max_features].to_s).to eq("log2")
    expect(p[:max_depth]).to eq(3)
    expect(p[:min_samples_leaf]).to eq(2)
    expect(p[:seed]).to eq(9)
    expect(p[:criterion].to_s).to eq("entropy")
    expect(p[:bootstrap]).to be_false
    # with_params CLONES: the receiver is untouched and still unfitted.
    expect(again.fitted?).to be_false
    expect(model.with_params({ n_estimators: 3 }).n_estimators).to eq(3)
    expect(model.n_estimators).to eq(7)

  it "clamps min_samples_leaf in the constructor, so params tells the truth" ->
    expect(RandomForestClassifier.new(5, nil, nil, 0).min_samples_leaf).to eq(1)
    expect(RandomForestClassifier.new(5, nil, nil, -4).min_samples_leaf).to eq(1)

  it "honours sample weights, and refuses an unusable vector" ->
    data = Fx.small
    ones = []
    data[:rows].each -> (r)
      ones.push(1)
    weighted = RandomForestClassifier.new(6, :all, nil, 1, 2)
    expect(weighted.fit(data[:rows], data[:labels], ones)).not_to be_nil
    # All-ones weights multiply into the bootstrap counts unchanged, so the
    # forest is the unweighted one exactly.
    plain = RandomForestClassifier.new(6, :all, nil, 1, 2)
    plain.fit(data[:rows], data[:labels])
    expect(Persist.dumps(weighted)).to eq(Persist.dumps(plain))
    short = RandomForestClassifier.new(6)
    expect(short.fit(data[:rows], data[:labels], [1, 2])).to be_nil
    expect(short.fitted?).to be_false

  it "grows an entropy forest as readily as a gini one" ->
    data = Fx.small
    model = RandomForestClassifier.new(6, :sqrt, nil, 1, 5, :entropy)
    expect(model.fit(data[:rows], data[:labels])).not_to be_nil
    expect(model.score(data[:rows], data[:labels]) > 0.to_f).to be_true

# --- The regressor's surface ----------------------------------------

describe "RandomForestRegressor" ->
  it "fits, predicts a number per row and scores an R²" ->
    data = Fx.small_reg
    model = RandomForestRegressor.new(9, nil, nil, 1, 4)
    expect(model.fit(data[:rows], data[:ys])).not_to be_nil
    expect(model.tree_count).to eq(9)
    expect(model.n_features).to eq(3)
    preds = model.predict(data[:rows])
    expect(preds.size).to eq(data[:rows].size)
    expect(model.score(data[:rows], data[:ys]) > 0.to_f).to be_true

  it "answers the contract and defaults to ten mse trees over all features" ->
    model = RandomForestRegressor.new
    expect(model.estimator_name).to eq("RandomForestRegressor")
    expect(model.supervised?).to be_true
    expect(model.supports_sample_weight?).to be_true
    p = model.params
    expect(p[:n_estimators]).to eq(10)
    expect(p[:max_features]).to be_nil
    expect(p[:criterion].to_s).to eq("mse")
    expect(p[:bootstrap]).to be_true

  it "round-trips every hyperparameter through with_params" ->
    model = RandomForestRegressor.new(4, 2, 5, 3, 11, :variance, false)
    p = model.with_params(model.params).params
    expect(p[:n_estimators]).to eq(4)
    expect(p[:max_features]).to eq(2)
    expect(p[:max_depth]).to eq(5)
    expect(p[:min_samples_leaf]).to eq(3)
    expect(p[:seed]).to eq(11)
    expect(p[:criterion].to_s).to eq("variance")
    expect(p[:bootstrap]).to be_false

  it "reports an out-of-bag R²" ->
    data = Fx.small_reg
    model = RandomForestRegressor.new(12, nil, nil, 1, 6)
    model.fit(data[:rows], data[:ys])
    expect(model.oob_score).not_to be_nil
    expect(model.oob_score <= 1.to_f).to be_true

# --- Degenerate input: nil, never a raise ---------------------------

describe "RandomForest degenerate input" ->
  it "returns nil before a fit, for every reader that needs one" ->
    model = RandomForestClassifier.new(5)
    data = Fx.small
    expect(model.predict(data[:rows])).to be_nil
    expect(model.predict_proba(data[:rows])).to be_nil
    expect(model.score(data[:rows], data[:labels])).to be_nil
    expect(model.tree_count).to be_nil
    expect(model.trees).to be_nil
    expect(model.classes).to be_nil
    expect(model.oob_score).to be_nil
    expect(RandomForestRegressor.new(5).predict(data[:rows])).to be_nil

  it "refuses an empty, a ragged or a misaligned training set" ->
    data = Fx.small
    empty = RandomForestClassifier.new(5)
    expect(empty.fit([], [])).to be_nil
    expect(empty.fitted?).to be_false
    misaligned = RandomForestClassifier.new(5)
    expect(misaligned.fit(data[:rows], ["a", "b"])).to be_nil
    ragged = RandomForestClassifier.new(5)
    expect(ragged.fit([[1, 2], [3]], ["a", "b"])).to be_nil
    expect(RandomForestRegressor.new(5).fit([], [])).to be_nil
    expect(RandomForestRegressor.new(5).fit(data[:rows], [1, 2])).to be_nil

  it "refuses to grow fewer than one tree" ->
    data = Fx.small
    none = RandomForestClassifier.new(0)
    expect(none.fit(data[:rows], data[:labels])).to be_nil
    expect(none.fitted?).to be_false
    # It is reported as it was SET, not quietly rounded up — a search that
    # produced 0 should see 0 come back.
    expect(none.params[:n_estimators]).to eq(0)
    expect(RandomForestClassifier.new(-3).fit(data[:rows], data[:labels])).to be_nil
    expect(RandomForestRegressor.new(0).fit(data[:rows], Fx.small_reg[:ys])).to be_nil

  it "refuses a criterion or a max_features setting it does not know" ->
    data = Fx.small
    expect(RandomForestClassifier.new(5, nil, nil, 1, 1, :mse).fit(data[:rows], data[:labels])).to be_nil
    expect(RandomForestClassifier.new(5, :bogus).fit(data[:rows], data[:labels])).to be_nil
    reg = Fx.small_reg
    expect(RandomForestRegressor.new(5, nil, nil, 1, 1, :gini).fit(reg[:rows], reg[:ys])).to be_nil
    expect(RandomForestRegressor.new(5, :nonsense).fit(reg[:rows], reg[:ys])).to be_nil

  it "returns nil for a query whose width is not the fitted width" ->
    data = Fx.small
    model = RandomForestClassifier.new(5, :all, nil, 1, 1)
    model.fit(data[:rows], data[:labels])
    expect(model.predict([[1, 2]])).to be_nil
    expect(model.predict_proba([[1, 2]])).to be_nil
    expect(model.score([[1, 2]], ["a"])).to be_nil

  it "grows a one-leaf forest rather than failing on a single-class target" ->
    rows = [[1, 1], [2, 2], [3, 3], [4, 4]]
    labels = ["a", "a", "a", "a"]
    model = RandomForestClassifier.new(4, :all, nil, 1, 1)
    expect(model.fit(rows, labels)).not_to be_nil
    expect(model.predict(rows).join(",")).to eq("a,a,a,a")

# --- Persistence -----------------------------------------------------

describe "RandomForest persistence" ->
  it "round-trips a classifier, every tree of it, predicting identically" ->
    data = Fx.small
    model = RandomForestClassifier.new(8, :sqrt, 3, 1, 17)
    model.fit(data[:rows], data[:labels])
    again = Fx.cycle(model)
    expect(again).not_to be_nil
    expect(again.persist_name).to eq("RandomForestClassifier")
    expect(again.tree_count).to eq(8)
    expect(Fx.preds(again, data[:rows])).to eq(Fx.preds(model, data[:rows]))
    # ... on rows the fit never saw, too.
    unseen = Fx.clf(12, 4242, 0, 3)
    expect(Fx.preds(again, unseen[:rows])).to eq(Fx.preds(model, unseen[:rows]))
    # ... and re-dumping what was loaded reproduces the payload exactly,
    # which pins every threshold in all eight trees.
    expect(Persist.dumps(again)).to eq(Persist.dumps(model))
    # The hyperparameters and the free holdout survive the trip.
    expect(again.params[:max_features].to_s).to eq("sqrt")
    expect(again.params[:max_depth]).to eq(3)
    expect(again.params[:seed]).to eq(17)
    expect(Fx.close?(again.oob_score, model.oob_score)).to be_true

  it "round-trips a regressor" ->
    data = Fx.small_reg
    model = RandomForestRegressor.new(8, nil, nil, 1, 17, nil, true)
    model.fit(data[:rows], data[:ys])
    again = Fx.cycle(model)
    expect(again).not_to be_nil
    expect(again.persist_name).to eq("RandomForestRegressor")
    expect(Fx.preds(again, data[:rows])).to eq(Fx.preds(model, data[:rows]))
    expect(Persist.dumps(again)).to eq(Persist.dumps(model))

  it "survives two full cycles unchanged" ->
    data = Fx.small
    model = RandomForestClassifier.new(6, :sqrt, nil, 1, 2)
    model.fit(data[:rows], data[:labels])
    twice = Fx.cycle(Fx.cycle(model))
    expect(Fx.preds(twice, data[:rows])).to eq(Fx.preds(model, data[:rows]))
    expect(Persist.dumps(twice)).to eq(Persist.dumps(model))

  it "refuses to dump an unfitted forest" ->
    expect(Persist.dumps(RandomForestClassifier.new(5))).to be_nil
    expect(Persist.dumps(RandomForestRegressor.new(5))).to be_nil

  it "does not mis-load a forest payload as a tree, or a tree as a forest" ->
    data = Fx.small
    forest = RandomForestClassifier.new(5, :all, nil, 1, 1)
    forest.fit(data[:rows], data[:labels])
    ftext = Persist.dumps(forest)
    tree = DecisionTreeClassifier.new
    tree.fit(data[:rows], data[:labels])
    ttext = Persist.dumps(tree)
    # A forest has no min_samples_split and no single `tree`; a tree has no
    # n_estimators and no `trees`. Each loader checks for its own state.
    expect(Persist.loads(ftext.split("o RandomForestClassifier").join("o DecisionTreeClassifier"))).to be_nil
    expect(Persist.loads(ttext.split("o DecisionTreeClassifier").join("o RandomForestClassifier"))).to be_nil
    # A CLASSIFIER forest relabelled as a REGRESSOR one is refused too: it
    # carries `classes`, and averaging labels is not a regression.
    expect(Persist.loads(ftext.split("o RandomForestClassifier").join("o RandomForestRegressor"))).to be_nil
    # ... while the honest payloads still load as exactly what they are.
    expect(Persist.loads(ftext).persist_name).to eq("RandomForestClassifier")

# --- Composition: it is an estimator like any other -----------------

describe "RandomForest in koala's generic tooling" ->
  it "works as the tail of a Pipeline, and exposes its knobs there" ->
    frame = DataFrame.new([[:a, [1, 2, 3, 4, 5, 6, 7, 8]], [:b, [2, 1, 4, 3, 6, 5, 8, 7]]])
    labels = ["x", "x", "x", "y", "y", "y", "y", "x"]
    pipe = Pipeline.new([[:scale, Scaler.new(:standard)], [:forest, RandomForestClassifier.new(6, :all, nil, 1, 3)]])
    expect(pipe.fit(frame, labels)).not_to be_nil
    expect(pipe.predict(frame).size).to eq(8)
    expect(pipe.score(frame, labels) > 0.to_f).to be_true
    expect(pipe.estimator_name).to eq("Pipeline")
    expect(pipe.supervised?).to be_true
    expect(pipe.supports_sample_weight?).to be_true
    # The forest's hyperparameters reach the pipeline's tunable surface
    # with no code in pipeline.w aware that forests exist.
    expect(pipe.params.key?("forest.n_estimators")).to be_true
    expect(pipe.params.key?("forest.max_features")).to be_true
    expect(pipe.with_params({ "forest.n_estimators": 3 }).step("forest").n_estimators).to eq(3)

  it "is tuned by GridSearch through the estimator contract alone" ->
    data = Fx.clf(30, 21, 10, 3)
    search = GridSearch.new(RandomForestClassifier.new(4, :all, nil, 1, 2), { max_depth: [1, 2, 3] }, 3)
    expect(search.fit(data[:rows], data[:labels])).not_to be_nil
    expect(search.size).to eq(3)
    expect(search.best_params).not_to be_nil
    expect(search.best_score).not_to be_nil
    expect(search.best_estimator.estimator_name).to eq("RandomForestClassifier")
    expect(search.estimator_name).to eq("GridSearch(RandomForestClassifier)")
    expect(search.predict(data[:rows]).size).to eq(30)

  it "searches max_features itself, the knob a forest exists for" ->
    data = Fx.clf(30, 21, 10, 4)
    search = GridSearch.new(RandomForestClassifier.new(4, nil, nil, 1, 2), { max_features: [:sqrt, :all] }, 3)
    expect(search.fit(data[:rows], data[:labels])).not_to be_nil
    expect(search.size).to eq(2)
    expect(search.best_params).not_to be_nil

  it "is cross-validated, including on stratified folds" ->
    data = Fx.clf(30, 21, 10, 3)
    model = RandomForestClassifier.new(4, :sqrt, nil, 1, 4)
    scores = CrossValidation.cross_val_score(model, data[:rows], data[:labels], StratifiedKFold.new(3))
    expect(scores).not_to be_nil
    expect(scores.size).to eq(3)
    every_fold = true
    scores.each -> (s)
      every_fold = false if s == nil
    expect(every_fold).to be_true
    expect(CrossValidation.cross_val_mean(model, data[:rows], data[:labels], 3)).not_to be_nil

  it "cross-validates the regressor on R², the same way the tree does" ->
    data = Fx.reg(30, 21, 5, 3)
    model = RandomForestRegressor.new(4, nil, nil, 1, 4)
    scores = CrossValidation.cross_val_score(model, data[:rows], data[:ys], 3)
    expect(scores).not_to be_nil
    expect(scores.size).to eq(3)

spec_summary
