/* Generated by scripts/gen_ast_schema.rb. Do not edit. */
#ifndef TUNGSTEN_AST_SCHEMA_GENERATED_H
#define TUNGSTEN_AST_SCHEMA_GENERATED_H

#include <stdint.h>

#define W_AST_SCHEMA_ABI_VERSION UINT32_C(1)
#define W_AST_SCHEMA_HASH UINT64_C(0xD050CBEA6A2DB0DF)
#define W_AST_KIND_MAX UINT32_C(147)

#endif
