/* Generated by scripts/gen_ast_schema.rb. Do not edit. */
#ifndef TUNGSTEN_AST_SCHEMA_GENERATED_H
#define TUNGSTEN_AST_SCHEMA_GENERATED_H

#include <stdint.h>

#define W_AST_SCHEMA_ABI_VERSION UINT32_C(2)
#define W_AST_SCHEMA_HASH UINT64_C(0x00002C5D9B2F7766)
#define W_AST_KIND_MAX UINT32_C(148)

static const uint8_t W_AST_KIND_WIDTH[W_AST_KIND_MAX + 1] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 2, 1, 3, 4, 3, 4, 1, 0, 1, 1, 6, 2, 3, 3, 0,
    1, 4, 0, 0, 3, 3, 0, 1, 1, 1, 1, 2, 3, 2, 2, 1,
    6, 1, 7, 1, 4, 2, 3, 1, 0, 1, 0, 5, 3, 1, 7, 2,
    1, 2, 0, 0, 1, 3, 2, 2, 6, 0, 2, 1, 1, 1, 2, 3,
    3, 1, 2, 0, 2, 1, 6, 5, 0, 0, 1, 1, 0, 0, 1, 2,
    1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 0, 2, 0, 3, 1,
    0, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 3, 3, 3, 0, 1,
    0, 2, 1, 1, 2
};

#endif
