# Heredoc bodies are opaque to every lexer. Token-looking content inside a
# long body must not become TYPE_HINT, regex, string, class, or nested
# heredoc tokens; only the closing delimiter resumes tokenization.

-> check(name, ok)
  if ok
    << "PASS " + name
  else
    << "FAIL " + name
    exit 1

payload = <<~JAVASCRIPT
  // pad_0000 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0001 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0002 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0003 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0004 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0005 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0006 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0007 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0008 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0009 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0010 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0011 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0012 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0013 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0014 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0015 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0016 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0017 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0018 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0019 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0020 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0021 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0022 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0023 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0024 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0025 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0026 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0027 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0028 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0029 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0030 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0031 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0032 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0033 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0034 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0035 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0036 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0037 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0038 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0039 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0040 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0041 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0042 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0043 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0044 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0045 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0046 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0047 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0048 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0049 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0050 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0051 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0052 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0053 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0054 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0055 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0056 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0057 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0058 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0059 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0060 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0061 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0062 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0063 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0064 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0065 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0066 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0067 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0068 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0069 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0070 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0071 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0072 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0073 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0074 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0075 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0076 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0077 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0078 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0079 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0080 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0081 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0082 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0083 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0084 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0085 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0086 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0087 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0088 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0089 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0090 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0091 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0092 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0093 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0094 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0095 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0096 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0097 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0098 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0099 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0100 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0101 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0102 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0103 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0104 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0105 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0106 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0107 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0108 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0109 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0110 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0111 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0112 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0113 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0114 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0115 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0116 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0117 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0118 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0119 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0120 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0121 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0122 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0123 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0124 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0125 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0126 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0127 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0128 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0129 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0130 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0131 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0132 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0133 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0134 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0135 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0136 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0137 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0138 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0139 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0140 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0141 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0142 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0143 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0144 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0145 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0146 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0147 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0148 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0149 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0150 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0151 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0152 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0153 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0154 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0155 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0156 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0157 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0158 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0159 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0160 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0161 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0162 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0163 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0164 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0165 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0166 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0167 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0168 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0169 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0170 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0171 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0172 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0173 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0174 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0175 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0176 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0177 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0178 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0179 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0180 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0181 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0182 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0183 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0184 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0185 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0186 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0187 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0188 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0189 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0190 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0191 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0192 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0193 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0194 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0195 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0196 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0197 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0198 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0199 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0200 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0201 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0202 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0203 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0204 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0205 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0206 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0207 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0208 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0209 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0210 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0211 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0212 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0213 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0214 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0215 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0216 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0217 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0218 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0219 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0220 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0221 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0222 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0223 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0224 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0225 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0226 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0227 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0228 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0229 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0230 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0231 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0232 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0233 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0234 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0235 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0236 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0237 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0238 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
  // pad_0239 [] ## i64: fake /regex[abc]/ "quote" <<~NESTED CamelCase
JAVASCRIPT

check("heredoc.opaque.long_body_size", payload.size() > 12000)
check("heredoc.opaque.first_line", payload.starts_with?("// pad_0000"))
check("heredoc.opaque.type_hint_text", payload.include?("## i64: fake"))
check("heredoc.opaque.camel_text", payload.include?(("Camel" + "Case")))
tail = "// pad_0239 \[] ## i64: fake /regex" + "\[" + "abc" + "]/ \"quote\" <<~NESTED CamelCase"
check("heredoc.opaque.last_line", payload.include?(tail))
