# String#scan over native regex literals (compiled lanes only: the
# tree-walker has no regex-literal AST support). Generated by
# scripts/gen_unicode_spec.py.

-> check(name, got, want)
  if got != want
    << "FAIL [name]: got=[got] want=[want]"
    exit(1)

check("scan digits", "a1b22c333".scan(/[0-9]+/), ["1", "22", "333"])
check("scan groups", "a=1,b=2".scan(/([a-z])=([0-9])/), [["a", "1"], ["b", "2"]])
check("scan no match", "abc".scan(/[0-9]/), [])
check("scan anchored", "aXbX".scan(/^./), ["a"])
check("scan empty advance", "ab".scan(/x*/), ["", "", ""])
check("scan utf8", ("é" * 3).scan("é"), ["é", "é", "é"])

<< "string_scan_spec: all checks passed"
