+ Tungsten
  auto :Atomic,       "atomic"
  auto :Array,        "array"
  auto :Base64,       "base64"
  auto :BigArray,     "big_array"
  auto :BlankSlate,   "blank_slate"
  auto :Bool,         "bool"
  auto :BoolArray,    "bool_array"
  auto :ByteArray,    "byte_array"
  auto :Char,         "char"
  auto :Channel,      "channel"
  auto :Class,        "class"
  auto :Closure,      "closure"
  auto :CIDR,         "cidr"
  auto :Color,        "color"
  auto :Crypto,       "crypto"
  auto :Currency,     "currency"
  auto :Date,         "date"
  auto :Digest,       "digest"
  auto :Duration,     "duration"
  auto :Error,        "error"
  auto :Float,        "float"
  auto :Hash,         "hash"
  auto :Hypercomplex, "numeric/hypercomplex"
  auto :Interval,     "numeric/interval"
  auto :IntervalF64,  "numeric/intervalf64"
  auto :IPv4,         "ipv4"
  auto :IPv6,         "ipv6"
  auto :Instant,      "instant"
  auto :Integer,      "integer"
  auto :JSON,         "json"
  auto :Math,         "math"
  auto :Matrix,       "matrix"
  auto :Mmap,         "mmap"
  # Scientific stack (flat core/)
  auto :LinAlg,       "linalg"
  auto :FFT,          "fft"
  auto :Special,      "special"
  auto :Stats,        "stats"
  auto :Tensor,       "tensor"
  auto :Dual,         "autodiff"
  auto :Tape,         "autodiff"
  auto :Autodiff,     "autodiff"
  auto :Solve,        "solve"
  auto :Optim,        "optim"
  auto :Interpolate,  "interpolate"
  auto :SciIO,        "io"
  auto :Plot,      "plot"
  auto :Sparse,       "sparse"
  auto :CUDA,         "cuda"
  auto :MAC,          "mac"
  auto :Module,       "module"
  auto :Nil,          "nil"
  auto :Number,       "number"
  auto :Object,       "object"
  auto :Path,         "path"
  auto :Quantity,     "quantity"
  auto :Measurement,  "measurement"
  auto :Calibration,  "calibration"
  auto :Random,       "random"
  auto :Range,        "range"
  auto :Regex,        "regex"
  auto :SmallArray,   "small_array"
  # string.w is the legacy API/design scaffold and is not accepted by the
  # current parser. Runtime-backed String dispatch loads this small native
  # implementation instead.
  auto :String,       "string_native"
  auto :StringBuffer, "string_buffer"
  auto :Symbol,       "symbol"
  auto :Thread,       "thread"
  auto :Token,        "token"
  auto :UUID,         "uuid"
  auto :Value,        "value"
  auto :Vector,       "vector"

  auto :BF16,         "numeric/bf16"

  auto :BigComplex,   "numeric/big_complex"
  auto :BigDecimal,   "numeric/big_decimal"
  auto :BigInt,       "numeric/big_int"

  # Hypercomplex tower — concrete subclasses live in the sibling
  # `numeric/hypercomplex/` directory; the abstract `Hypercomplex<T>`
  # base stays at `numeric/hypercomplex.w` as the orchestrator.
  auto :Centumduodetrigintanion,   "numeric/hypercomplex/centumduodetrigintanion"
  auto :Complex,                   "numeric/hypercomplex/complex"
  auto :Ducentiquinquagintasexion, "numeric/hypercomplex/ducentiquinquagintasexion"
  auto :Octonion,                  "numeric/hypercomplex/octonion"
  auto :Quaternion,                "numeric/hypercomplex/quaternion"
  auto :QuaternionMetal,           "numeric/hypercomplex/quaternion_metal"
  auto :Sedenion,                  "numeric/hypercomplex/sedenion"
  auto :Sexagintaquatronion,       "numeric/hypercomplex/sexagintaquatronion"
  auto :Trigintaduonion,           "numeric/hypercomplex/trigintaduonion"

  auto :Vec2,         "numeric/vec2"
  auto :Vec3,         "numeric/vec3"
  auto :Vec4,         "numeric/vec4"

  auto :Mat,          "numeric/mat"
  auto :Mat2,         "numeric/mat2"
  auto :Mat3,         "numeric/mat3"
  auto :Mat4,         "numeric/mat4"

  auto :Decimal,      "numeric/decimal"
  auto :Decimal32,    "numeric/decimal32"
  auto :Decimal64,    "numeric/decimal64"
  auto :Decimal128,   "numeric/decimal128"

  auto :Float,        "numeric/float"
  auto :Float16,      "numeric/float16"
  auto :Float32,      "numeric/float32"
  auto :Float64,      "numeric/float64"
  auto :Float80,      "numeric/float80"
  auto :Float128,     "numeric/float128"
  auto :Float256,     "numeric/float256"

  auto :Real,         "numeric/real"

  auto :Comparable,   "traits/comparable"
  auto :Enumerable,   "traits/enumerable"

  auto :ArgumentError, "argument_error"
  auto :RangeError,    "range_error"
  auto :TypeError,     "type_error"

  -> .root
    Path(__project_root)
