# Generated by scripts/gen_wire_constructors.rb. Do not edit.
# Fields are stored in the canonical order recorded in
# compiler/wire_instruction_schema.json.

-> wire_make_add_i64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 1, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_add_i64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_add_i64(lhs, rhs, temp))

-> wire_make_addcarry_u64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 2, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_addcarry_u64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_addcarry_u64(lhs, rhs, temp))

-> wire_make_alloca_array(count, ptr)
  handle = ccall_rawargs("w_wire_alloc", 3, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :count, count)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ptr, ptr)
  handle

-> emit_wire_alloca_array(f, count, ptr)
  current_block(f)[:instructions].push(wire_make_alloca_array(count, ptr))

-> wire_make_alloca_i64(ptr)
  handle = ccall_rawargs("w_wire_alloc", 4, 1)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ptr, ptr)
  handle

-> emit_wire_alloca_i64(f, ptr)
  current_block(f)[:instructions].push(wire_make_alloca_i64(ptr))

-> wire_make_and_i1(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 5, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_and_i1(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_and_i1(lhs, rhs, temp))

-> wire_make_and_i64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 6, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_and_i64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_and_i64(lhs, rhs, temp))

-> wire_make_argv_init()
  handle = ccall_rawargs("w_wire_alloc", 7, 0)
  handle

-> emit_wire_argv_init(f)
  current_block(f)[:instructions].push(wire_make_argv_init())

-> wire_make_arr_data_ptr(arr, temp)
  handle = ccall_rawargs("w_wire_alloc", 8, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arr, arr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_arr_data_ptr(f, arr, temp)
  current_block(f)[:instructions].push(wire_make_arr_data_ptr(arr, temp))

-> wire_make_array_get_inline(arr, idx, s, temp)
  handle = ccall_rawargs("w_wire_alloc", 9, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arr, arr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :idx, idx)
  ccall_nobox("w_wire_field_store_at", handle, 2, :s, wire_sequence(s))
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_array_get_inline(f, arr, idx, s, temp)
  current_block(f)[:instructions].push(wire_make_array_get_inline(arr, idx, s, temp))

-> wire_make_array_size_raw(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 10, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_array_size_raw(f, temp, value)
  current_block(f)[:instructions].push(wire_make_array_size_raw(temp, value))

-> wire_make_asm_add_n(ap, bp, n, outp, temp)
  handle = ccall_rawargs("w_wire_alloc", 11, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ap, ap)
  ccall_nobox("w_wire_field_store_at", handle, 1, :bp, bp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :n, n)
  ccall_nobox("w_wire_field_store_at", handle, 3, :outp, outp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp, temp)
  handle

-> emit_wire_asm_add_n(f, ap, bp, n, outp, temp)
  current_block(f)[:instructions].push(wire_make_asm_add_n(ap, bp, n, outp, temp))

-> wire_make_asm_add_no(aoff, ap, boff, bp, n, ooff, outp, temp)
  handle = ccall_rawargs("w_wire_alloc", 12, 8)
  ccall_nobox("w_wire_field_store_at", handle, 0, :aoff, aoff)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ap, ap)
  ccall_nobox("w_wire_field_store_at", handle, 2, :boff, boff)
  ccall_nobox("w_wire_field_store_at", handle, 3, :bp, bp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :n, n)
  ccall_nobox("w_wire_field_store_at", handle, 5, :ooff, ooff)
  ccall_nobox("w_wire_field_store_at", handle, 6, :outp, outp)
  ccall_nobox("w_wire_field_store_at", handle, 7, :temp, temp)
  handle

-> emit_wire_asm_add_no(f, aoff, ap, boff, bp, n, ooff, outp, temp)
  current_block(f)[:instructions].push(wire_make_asm_add_no(aoff, ap, boff, bp, n, ooff, outp, temp))

-> wire_make_asm_add_test(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 13, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_asm_add_test(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_asm_add_test(lhs, rhs, temp))

-> wire_make_asm_addmul1(aoff, ap, bsc, n, ooff, outp, temp)
  handle = ccall_rawargs("w_wire_alloc", 14, 7)
  ccall_nobox("w_wire_field_store_at", handle, 0, :aoff, aoff)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ap, ap)
  ccall_nobox("w_wire_field_store_at", handle, 2, :bsc, bsc)
  ccall_nobox("w_wire_field_store_at", handle, 3, :n, n)
  ccall_nobox("w_wire_field_store_at", handle, 4, :ooff, ooff)
  ccall_nobox("w_wire_field_store_at", handle, 5, :outp, outp)
  ccall_nobox("w_wire_field_store_at", handle, 6, :temp, temp)
  handle

-> emit_wire_asm_addmul1(f, aoff, ap, bsc, n, ooff, outp, temp)
  current_block(f)[:instructions].push(wire_make_asm_addmul1(aoff, ap, bsc, n, ooff, outp, temp))

-> wire_make_asm_gold_stage(hq, nb, temp, twp, vp)
  handle = ccall_rawargs("w_wire_alloc", 15, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :hq, hq)
  ccall_nobox("w_wire_field_store_at", handle, 1, :nb, nb)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :twp, twp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :vp, vp)
  handle

-> emit_wire_asm_gold_stage(f, hq, nb, temp, twp, vp)
  current_block(f)[:instructions].push(wire_make_asm_gold_stage(hq, nb, temp, twp, vp))

-> wire_make_asm_gold_stage_inv(hq, ivp, nb, temp, twp, vp)
  handle = ccall_rawargs("w_wire_alloc", 16, 6)
  ccall_nobox("w_wire_field_store_at", handle, 0, :hq, hq)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ivp, ivp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :nb, nb)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :twp, twp)
  ccall_nobox("w_wire_field_store_at", handle, 5, :vp, vp)
  handle

-> emit_wire_asm_gold_stage_inv(f, hq, ivp, nb, temp, twp, vp)
  current_block(f)[:instructions].push(wire_make_asm_gold_stage_inv(hq, ivp, nb, temp, twp, vp))

-> wire_make_asm_mulbase(aoff, ap, boff, bp, na, nb, ooff, outp, temp)
  handle = ccall_rawargs("w_wire_alloc", 17, 9)
  ccall_nobox("w_wire_field_store_at", handle, 0, :aoff, aoff)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ap, ap)
  ccall_nobox("w_wire_field_store_at", handle, 2, :boff, boff)
  ccall_nobox("w_wire_field_store_at", handle, 3, :bp, bp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :na, na)
  ccall_nobox("w_wire_field_store_at", handle, 5, :nb, nb)
  ccall_nobox("w_wire_field_store_at", handle, 6, :ooff, ooff)
  ccall_nobox("w_wire_field_store_at", handle, 7, :outp, outp)
  ccall_nobox("w_wire_field_store_at", handle, 8, :temp, temp)
  handle

-> emit_wire_asm_mulbase(f, aoff, ap, boff, bp, na, nb, ooff, outp, temp)
  current_block(f)[:instructions].push(wire_make_asm_mulbase(aoff, ap, boff, bp, na, nb, ooff, outp, temp))

-> wire_make_asm_neon_gadd2(ap, bp, n, outp, temp)
  handle = ccall_rawargs("w_wire_alloc", 18, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ap, ap)
  ccall_nobox("w_wire_field_store_at", handle, 1, :bp, bp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :n, n)
  ccall_nobox("w_wire_field_store_at", handle, 3, :outp, outp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp, temp)
  handle

-> emit_wire_asm_neon_gadd2(f, ap, bp, n, outp, temp)
  current_block(f)[:instructions].push(wire_make_asm_neon_gadd2(ap, bp, n, outp, temp))

-> wire_make_asm_neon_ntt_stage(hq, nb, temp, twp, vp)
  handle = ccall_rawargs("w_wire_alloc", 19, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :hq, hq)
  ccall_nobox("w_wire_field_store_at", handle, 1, :nb, nb)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :twp, twp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :vp, vp)
  handle

-> emit_wire_asm_neon_ntt_stage(f, hq, nb, temp, twp, vp)
  current_block(f)[:instructions].push(wire_make_asm_neon_ntt_stage(hq, nb, temp, twp, vp))

-> wire_make_asm_neon_redc(ap, bp, n, outp, temp)
  handle = ccall_rawargs("w_wire_alloc", 20, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ap, ap)
  ccall_nobox("w_wire_field_store_at", handle, 1, :bp, bp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :n, n)
  ccall_nobox("w_wire_field_store_at", handle, 3, :outp, outp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp, temp)
  handle

-> emit_wire_asm_neon_redc(f, ap, bp, n, outp, temp)
  current_block(f)[:instructions].push(wire_make_asm_neon_redc(ap, bp, n, outp, temp))

-> wire_make_asm_neon_umull(ap, bp, n, outp, temp)
  handle = ccall_rawargs("w_wire_alloc", 21, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ap, ap)
  ccall_nobox("w_wire_field_store_at", handle, 1, :bp, bp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :n, n)
  ccall_nobox("w_wire_field_store_at", handle, 3, :outp, outp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp, temp)
  handle

-> emit_wire_asm_neon_umull(f, ap, bp, n, outp, temp)
  current_block(f)[:instructions].push(wire_make_asm_neon_umull(ap, bp, n, outp, temp))

-> wire_make_asm_sub_no(aoff, ap, boff, bp, n, ooff, outp, temp)
  handle = ccall_rawargs("w_wire_alloc", 22, 8)
  ccall_nobox("w_wire_field_store_at", handle, 0, :aoff, aoff)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ap, ap)
  ccall_nobox("w_wire_field_store_at", handle, 2, :boff, boff)
  ccall_nobox("w_wire_field_store_at", handle, 3, :bp, bp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :n, n)
  ccall_nobox("w_wire_field_store_at", handle, 5, :ooff, ooff)
  ccall_nobox("w_wire_field_store_at", handle, 6, :outp, outp)
  ccall_nobox("w_wire_field_store_at", handle, 7, :temp, temp)
  handle

-> emit_wire_asm_sub_no(f, aoff, ap, boff, bp, n, ooff, outp, temp)
  current_block(f)[:instructions].push(wire_make_asm_sub_no(aoff, ap, boff, bp, n, ooff, outp, temp))

-> wire_make_big_array_get_inline(arr, bits, idx, idx_raw, s, signed, temp)
  handle = ccall_rawargs("w_wire_alloc", 23, 7)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arr, arr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :bits, bits)
  ccall_nobox("w_wire_field_store_at", handle, 2, :idx, idx)
  ccall_nobox("w_wire_field_store_at", handle, 3, :idx_raw, idx_raw)
  ccall_nobox("w_wire_field_store_at", handle, 4, :s, wire_sequence(s))
  ccall_nobox("w_wire_field_store_at", handle, 5, :signed, signed)
  ccall_nobox("w_wire_field_store_at", handle, 6, :temp, temp)
  handle

-> emit_wire_big_array_get_inline(f, arr, bits, idx, idx_raw, s, signed, temp)
  current_block(f)[:instructions].push(wire_make_big_array_get_inline(arr, bits, idx, idx_raw, s, signed, temp))

-> wire_make_bigint_literal_i64(byte_len, slot_id, string_id, temp, temp_ptr)
  handle = ccall_rawargs("w_wire_alloc", 24, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :byte_len, byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 1, :slot_id, slot_id)
  ccall_nobox("w_wire_field_store_at", handle, 2, :string_id, string_id)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp_ptr, temp_ptr)
  handle

-> emit_wire_bigint_literal_i64(f, byte_len, slot_id, string_id, temp, temp_ptr)
  current_block(f)[:instructions].push(wire_make_bigint_literal_i64(byte_len, slot_id, string_id, temp, temp_ptr))

-> wire_make_bitcast_f16_i16(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 25, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_bitcast_f16_i16(f, temp, value)
  current_block(f)[:instructions].push(wire_make_bitcast_f16_i16(temp, value))

-> wire_make_bitcast_f32_i32(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 26, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_bitcast_f32_i32(f, temp, value)
  current_block(f)[:instructions].push(wire_make_bitcast_f32_i32(temp, value))

-> wire_make_bitcast_f64_i64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 27, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_bitcast_f64_i64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_bitcast_f64_i64(temp, value))

-> wire_make_bitcast_i16_f16(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 28, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_bitcast_i16_f16(f, temp, value)
  current_block(f)[:instructions].push(wire_make_bitcast_i16_f16(temp, value))

-> wire_make_bitcast_i32_f32(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 29, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_bitcast_i32_f32(f, temp, value)
  current_block(f)[:instructions].push(wire_make_bitcast_i32_f32(temp, value))

-> wire_make_bitcast_i64_f64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 30, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_bitcast_i64_f64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_bitcast_i64_f64(temp, value))

-> wire_make_bool_array_get_inline(arr, as_i1, idx, temp)
  handle = ccall_rawargs("w_wire_alloc", 31, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arr, arr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :as_i1, as_i1)
  ccall_nobox("w_wire_field_store_at", handle, 2, :idx, idx)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_bool_array_get_inline(f, arr, as_i1, idx, temp)
  current_block(f)[:instructions].push(wire_make_bool_array_get_inline(arr, as_i1, idx, temp))

-> wire_make_bool_array_set_inline(arr, idx, temp, val)
  handle = ccall_rawargs("w_wire_alloc", 32, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arr, arr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :idx, idx)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :val, val)
  handle

-> emit_wire_bool_array_set_inline(f, arr, idx, temp, val)
  current_block(f)[:instructions].push(wire_make_bool_array_set_inline(arr, idx, temp, val))

-> wire_make_br(label, novec, unroll_count)
  handle = ccall_rawargs("w_wire_alloc", 33, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :label, label)
  ccall_nobox("w_wire_field_store_at", handle, 1, :novec, novec)
  ccall_nobox("w_wire_field_store_at", handle, 2, :unroll_count, unroll_count)
  handle

-> emit_wire_br(f, label, novec, unroll_count)
  current_block(f)[:instructions].push(wire_make_br(label, novec, unroll_count))

-> wire_make_builtin_class_init(class_name, name_byte_len, name_str_id)
  handle = ccall_rawargs("w_wire_alloc", 34, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :class_name, class_name)
  ccall_nobox("w_wire_field_store_at", handle, 1, :name_byte_len, name_byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 2, :name_str_id, name_str_id)
  handle

-> emit_wire_builtin_class_init(f, class_name, name_byte_len, name_str_id)
  current_block(f)[:instructions].push(wire_make_builtin_class_init(class_name, name_byte_len, name_str_id))

-> wire_make_call_direct_i64(arg_types, args, call_conv, loc_site_id, name, src_col, src_line, temp)
  handle = ccall_rawargs("w_wire_alloc", 35, 8)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arg_types, wire_sequence(arg_types))
  ccall_nobox("w_wire_field_store_at", handle, 1, :args, wire_sequence(args))
  ccall_nobox("w_wire_field_store_at", handle, 2, :call_conv, call_conv)
  ccall_nobox("w_wire_field_store_at", handle, 3, :loc_site_id, loc_site_id)
  ccall_nobox("w_wire_field_store_at", handle, 4, :name, name)
  ccall_nobox("w_wire_field_store_at", handle, 5, :src_col, src_col)
  ccall_nobox("w_wire_field_store_at", handle, 6, :src_line, src_line)
  ccall_nobox("w_wire_field_store_at", handle, 7, :temp, temp)
  handle

-> emit_wire_call_direct_i64(f, arg_types, args, call_conv, loc_site_id, name, src_col, src_line, temp)
  current_block(f)[:instructions].push(wire_make_call_direct_i64(arg_types, args, call_conv, loc_site_id, name, src_col, src_line, temp))

-> wire_make_call_direct_i64_ptr1(arg, name, temp)
  handle = ccall_rawargs("w_wire_alloc", 36, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arg, arg)
  ccall_nobox("w_wire_field_store_at", handle, 1, :name, name)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_call_direct_i64_ptr1(f, arg, name, temp)
  current_block(f)[:instructions].push(wire_make_call_direct_i64_ptr1(arg, name, temp))

-> wire_make_call_direct_ptr(args, name, temp)
  handle = ccall_rawargs("w_wire_alloc", 37, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :args, wire_sequence(args))
  ccall_nobox("w_wire_field_store_at", handle, 1, :name, name)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_call_direct_ptr(f, args, name, temp)
  current_block(f)[:instructions].push(wire_make_call_direct_ptr(args, name, temp))

-> wire_make_call_direct_void(args, name)
  handle = ccall_rawargs("w_wire_alloc", 38, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :args, wire_sequence(args))
  ccall_nobox("w_wire_field_store_at", handle, 1, :name, name)
  handle

-> emit_wire_call_direct_void(f, args, name)
  current_block(f)[:instructions].push(wire_make_call_direct_void(args, name))

-> wire_make_call_direct_void_ptr1(arg, name)
  handle = ccall_rawargs("w_wire_alloc", 39, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arg, arg)
  ccall_nobox("w_wire_field_store_at", handle, 1, :name, name)
  handle

-> emit_wire_call_direct_void_ptr1(f, arg, name)
  current_block(f)[:instructions].push(wire_make_call_direct_void_ptr1(arg, name))

-> wire_make_call_fused_out_reuse(bits, cap, slot, temp)
  handle = ccall_rawargs("w_wire_alloc", 40, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :bits, bits)
  ccall_nobox("w_wire_field_store_at", handle, 1, :cap, cap)
  ccall_nobox("w_wire_field_store_at", handle, 2, :slot, slot)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_call_fused_out_reuse(f, bits, cap, slot, temp)
  current_block(f)[:instructions].push(wire_make_call_fused_out_reuse(bits, cap, slot, temp))

-> wire_make_call_libm_f64(lhs, name, rhs, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 41, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :name, name)
  ccall_nobox("w_wire_field_store_at", handle, 2, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :value, value)
  handle

-> emit_wire_call_libm_f64(f, lhs, name, rhs, temp, value)
  current_block(f)[:instructions].push(wire_make_call_libm_f64(lhs, name, rhs, temp, value))

-> wire_make_call_loc_set_col(col, file_byte_len, file_str_id, line, temp_ptr)
  handle = ccall_rawargs("w_wire_alloc", 42, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :col, col)
  ccall_nobox("w_wire_field_store_at", handle, 1, :file_byte_len, file_byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 2, :file_str_id, file_str_id)
  ccall_nobox("w_wire_field_store_at", handle, 3, :line, line)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp_ptr, temp_ptr)
  handle

-> emit_wire_call_loc_set_col(f, col, file_byte_len, file_str_id, line, temp_ptr)
  current_block(f)[:instructions].push(wire_make_call_loc_set_col(col, file_byte_len, file_str_id, line, temp_ptr))

-> wire_make_call_method_i64(args, construct_class, construct_fn, devirt_class, devirt_fn, ic_id, method_name_val, receiver, scalar_source_argc1, scalar_source_argc2, src_col, src_line, temp, temp_args_val)
  handle = ccall_rawargs("w_wire_alloc", 43, 14)
  ccall_nobox("w_wire_field_store_at", handle, 0, :args, wire_sequence(args))
  ccall_nobox("w_wire_field_store_at", handle, 1, :construct_class, construct_class)
  ccall_nobox("w_wire_field_store_at", handle, 2, :construct_fn, construct_fn)
  ccall_nobox("w_wire_field_store_at", handle, 3, :devirt_class, devirt_class)
  ccall_nobox("w_wire_field_store_at", handle, 4, :devirt_fn, devirt_fn)
  ccall_nobox("w_wire_field_store_at", handle, 5, :ic_id, ic_id)
  ccall_nobox("w_wire_field_store_at", handle, 6, :method_name_val, method_name_val)
  ccall_nobox("w_wire_field_store_at", handle, 7, :receiver, receiver)
  ccall_nobox("w_wire_field_store_at", handle, 8, :scalar_source_argc1, scalar_source_argc1)
  ccall_nobox("w_wire_field_store_at", handle, 9, :scalar_source_argc2, scalar_source_argc2)
  ccall_nobox("w_wire_field_store_at", handle, 10, :src_col, src_col)
  ccall_nobox("w_wire_field_store_at", handle, 11, :src_line, src_line)
  ccall_nobox("w_wire_field_store_at", handle, 12, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 13, :temp_args_val, temp_args_val)
  handle

-> emit_wire_call_method_i64(f, args, construct_class, construct_fn, devirt_class, devirt_fn, ic_id, method_name_val, receiver, scalar_source_argc1, scalar_source_argc2, src_col, src_line, temp, temp_args_val)
  current_block(f)[:instructions].push(wire_make_call_method_i64(args, construct_class, construct_fn, devirt_class, devirt_fn, ic_id, method_name_val, receiver, scalar_source_argc1, scalar_source_argc2, src_col, src_line, temp, temp_args_val))

-> wire_make_call_num_to_f64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 44, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_call_num_to_f64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_call_num_to_f64(temp, value))

-> wire_make_call_recycle_or_new_array(temp)
  handle = ccall_rawargs("w_wire_alloc", 45, 1)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  handle

-> emit_wire_call_recycle_or_new_array(f, temp)
  current_block(f)[:instructions].push(wire_make_call_recycle_or_new_array(temp))

-> wire_make_call_recycle_or_new_hash(temp)
  handle = ccall_rawargs("w_wire_alloc", 46, 1)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  handle

-> emit_wire_call_recycle_or_new_hash(f, temp)
  current_block(f)[:instructions].push(wire_make_call_recycle_or_new_hash(temp))

-> wire_make_call_recycle_or_new_strbuf(cap, temp)
  handle = ccall_rawargs("w_wire_alloc", 47, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :cap, cap)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_call_recycle_or_new_strbuf(f, cap, temp)
  current_block(f)[:instructions].push(wire_make_call_recycle_or_new_strbuf(cap, temp))

-> wire_make_call_recycle_or_new_typed(bits, cap, temp)
  handle = ccall_rawargs("w_wire_alloc", 48, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :bits, bits)
  ccall_nobox("w_wire_field_store_at", handle, 1, :cap, cap)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_call_recycle_or_new_typed(f, bits, cap, temp)
  current_block(f)[:instructions].push(wire_make_call_recycle_or_new_typed(bits, cap, temp))

-> wire_make_call_reuse_and_drain_or_new_hash(slot, temp)
  handle = ccall_rawargs("w_wire_alloc", 49, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :slot, slot)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_call_reuse_and_drain_or_new_hash(f, slot, temp)
  current_block(f)[:instructions].push(wire_make_call_reuse_and_drain_or_new_hash(slot, temp))

-> wire_make_call_reuse_or_new_array(slot, temp)
  handle = ccall_rawargs("w_wire_alloc", 50, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :slot, slot)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_call_reuse_or_new_array(f, slot, temp)
  current_block(f)[:instructions].push(wire_make_call_reuse_or_new_array(slot, temp))

-> wire_make_call_reuse_or_new_hash(slot, temp)
  handle = ccall_rawargs("w_wire_alloc", 51, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :slot, slot)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_call_reuse_or_new_hash(f, slot, temp)
  current_block(f)[:instructions].push(wire_make_call_reuse_or_new_hash(slot, temp))

-> wire_make_call_reuse_or_new_strbuf(cap, slot, temp)
  handle = ccall_rawargs("w_wire_alloc", 52, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :cap, cap)
  ccall_nobox("w_wire_field_store_at", handle, 1, :slot, slot)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_call_reuse_or_new_strbuf(f, cap, slot, temp)
  current_block(f)[:instructions].push(wire_make_call_reuse_or_new_strbuf(cap, slot, temp))

-> wire_make_call_reuse_or_new_typed(bits, cap, slot, temp)
  handle = ccall_rawargs("w_wire_alloc", 53, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :bits, bits)
  ccall_nobox("w_wire_field_store_at", handle, 1, :cap, cap)
  ccall_nobox("w_wire_field_store_at", handle, 2, :slot, slot)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_call_reuse_or_new_typed(f, bits, cap, slot, temp)
  current_block(f)[:instructions].push(wire_make_call_reuse_or_new_typed(bits, cap, slot, temp))

-> wire_make_class_add_ivar(class_temp, ivar_byte_len, ivar_str_id)
  handle = ccall_rawargs("w_wire_alloc", 54, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :class_temp, class_temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ivar_byte_len, ivar_byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 2, :ivar_str_id, ivar_str_id)
  handle

-> emit_wire_class_add_ivar(f, class_temp, ivar_byte_len, ivar_str_id)
  current_block(f)[:instructions].push(wire_make_class_add_ivar(class_temp, ivar_byte_len, ivar_str_id))

-> wire_make_class_add_method(arity, class_temp, fn_name, method_byte_len, method_str_id, min_arity, splat_index)
  handle = ccall_rawargs("w_wire_alloc", 55, 7)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arity, arity)
  ccall_nobox("w_wire_field_store_at", handle, 1, :class_temp, class_temp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :fn_name, fn_name)
  ccall_nobox("w_wire_field_store_at", handle, 3, :method_byte_len, method_byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 4, :method_str_id, method_str_id)
  ccall_nobox("w_wire_field_store_at", handle, 5, :min_arity, min_arity)
  ccall_nobox("w_wire_field_store_at", handle, 6, :splat_index, splat_index)
  handle

-> emit_wire_class_add_method(f, arity, class_temp, fn_name, method_byte_len, method_str_id, min_arity, splat_index)
  current_block(f)[:instructions].push(wire_make_class_add_method(arity, class_temp, fn_name, method_byte_len, method_str_id, min_arity, splat_index))

-> wire_make_class_add_static_method(arity, class_temp, fn_name, method_byte_len, method_str_id, min_arity, splat_index)
  handle = ccall_rawargs("w_wire_alloc", 56, 7)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arity, arity)
  ccall_nobox("w_wire_field_store_at", handle, 1, :class_temp, class_temp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :fn_name, fn_name)
  ccall_nobox("w_wire_field_store_at", handle, 3, :method_byte_len, method_byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 4, :method_str_id, method_str_id)
  ccall_nobox("w_wire_field_store_at", handle, 5, :min_arity, min_arity)
  ccall_nobox("w_wire_field_store_at", handle, 6, :splat_index, splat_index)
  handle

-> emit_wire_class_add_static_method(f, arity, class_temp, fn_name, method_byte_len, method_str_id, min_arity, splat_index)
  current_block(f)[:instructions].push(wire_make_class_add_static_method(arity, class_temp, fn_name, method_byte_len, method_str_id, min_arity, splat_index))

-> wire_make_class_new(name_byte_len, name_str_id, super_reg, temp)
  handle = ccall_rawargs("w_wire_alloc", 57, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :name_byte_len, name_byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 1, :name_str_id, name_str_id)
  ccall_nobox("w_wire_field_store_at", handle, 2, :super_reg, super_reg)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_class_new(f, name_byte_len, name_str_id, super_reg, temp)
  current_block(f)[:instructions].push(wire_make_class_new(name_byte_len, name_str_id, super_reg, temp))

-> wire_make_class_store(class_name, value)
  handle = ccall_rawargs("w_wire_alloc", 58, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :class_name, class_name)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_class_store(f, class_name, value)
  current_block(f)[:instructions].push(wire_make_class_store(class_name, value))

-> wire_make_cleanup_pop()
  handle = ccall_rawargs("w_wire_alloc", 59, 0)
  handle

-> emit_wire_cleanup_pop(f)
  current_block(f)[:instructions].push(wire_make_cleanup_pop())

-> wire_make_closure_new(block_arity, capture_count, captures_ptr, fn_name, temp)
  handle = ccall_rawargs("w_wire_alloc", 60, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :block_arity, block_arity)
  ccall_nobox("w_wire_field_store_at", handle, 1, :capture_count, capture_count)
  ccall_nobox("w_wire_field_store_at", handle, 2, :captures_ptr, captures_ptr)
  ccall_nobox("w_wire_field_store_at", handle, 3, :fn_name, fn_name)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp, temp)
  handle

-> emit_wire_closure_new(f, block_arity, capture_count, captures_ptr, fn_name, temp)
  current_block(f)[:instructions].push(wire_make_closure_new(block_arity, capture_count, captures_ptr, fn_name, temp))

-> wire_make_cond_br(cond, else_label, prof, then_label)
  handle = ccall_rawargs("w_wire_alloc", 61, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :cond, cond)
  ccall_nobox("w_wire_field_store_at", handle, 1, :else_label, else_label)
  ccall_nobox("w_wire_field_store_at", handle, 2, :prof, prof)
  ccall_nobox("w_wire_field_store_at", handle, 3, :then_label, then_label)
  handle

-> emit_wire_cond_br(f, cond, else_label, prof, then_label)
  current_block(f)[:instructions].push(wire_make_cond_br(cond, else_label, prof, then_label))

-> wire_make_const_char(codepoint, temp)
  handle = ccall_rawargs("w_wire_alloc", 62, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :codepoint, codepoint)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_const_char(f, codepoint, temp)
  current_block(f)[:instructions].push(wire_make_const_char(codepoint, temp))

-> wire_make_const_color(a, b, g, r, temp)
  handle = ccall_rawargs("w_wire_alloc", 63, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :a, a)
  ccall_nobox("w_wire_field_store_at", handle, 1, :b, b)
  ccall_nobox("w_wire_field_store_at", handle, 2, :g, g)
  ccall_nobox("w_wire_field_store_at", handle, 3, :r, r)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp, temp)
  handle

-> emit_wire_const_color(f, a, b, g, r, temp)
  current_block(f)[:instructions].push(wire_make_const_color(a, b, g, r, temp))

-> wire_make_const_currency(scale, sig, symbol_id, temp)
  handle = ccall_rawargs("w_wire_alloc", 64, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :scale, scale)
  ccall_nobox("w_wire_field_store_at", handle, 1, :sig, sig)
  ccall_nobox("w_wire_field_store_at", handle, 2, :symbol_id, symbol_id)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_const_currency(f, scale, sig, symbol_id, temp)
  current_block(f)[:instructions].push(wire_make_const_currency(scale, sig, symbol_id, temp))

-> wire_make_const_date(day, hour, min, month, sec, temp, tz, year)
  handle = ccall_rawargs("w_wire_alloc", 65, 8)
  ccall_nobox("w_wire_field_store_at", handle, 0, :day, day)
  ccall_nobox("w_wire_field_store_at", handle, 1, :hour, hour)
  ccall_nobox("w_wire_field_store_at", handle, 2, :min, min)
  ccall_nobox("w_wire_field_store_at", handle, 3, :month, month)
  ccall_nobox("w_wire_field_store_at", handle, 4, :sec, sec)
  ccall_nobox("w_wire_field_store_at", handle, 5, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 6, :tz, tz)
  ccall_nobox("w_wire_field_store_at", handle, 7, :year, year)
  handle

-> emit_wire_const_date(f, day, hour, min, month, sec, temp, tz, year)
  current_block(f)[:instructions].push(wire_make_const_date(day, hour, min, month, sec, temp, tz, year))

-> wire_make_const_decimal(scale, sig, temp)
  handle = ccall_rawargs("w_wire_alloc", 66, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :scale, scale)
  ccall_nobox("w_wire_field_store_at", handle, 1, :sig, sig)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_const_decimal(f, scale, sig, temp)
  current_block(f)[:instructions].push(wire_make_const_decimal(scale, sig, temp))

-> wire_make_const_duration_months_ms(months, ms, temp)
  handle = ccall_rawargs("w_wire_alloc", 67, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :months, months)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ms, ms)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_const_duration_months_ms(f, months, ms, temp)
  current_block(f)[:instructions].push(wire_make_const_duration_months_ms(months, ms, temp))

-> wire_make_const_duration_ns(ns, temp)
  handle = ccall_rawargs("w_wire_alloc", 68, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ns, ns)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_const_duration_ns(f, ns, temp)
  current_block(f)[:instructions].push(wire_make_const_duration_ns(ns, temp))

-> wire_make_const_ipv4(a, b, c, cidr, d, temp)
  handle = ccall_rawargs("w_wire_alloc", 69, 6)
  ccall_nobox("w_wire_field_store_at", handle, 0, :a, a)
  ccall_nobox("w_wire_field_store_at", handle, 1, :b, b)
  ccall_nobox("w_wire_field_store_at", handle, 2, :c, c)
  ccall_nobox("w_wire_field_store_at", handle, 3, :cidr, cidr)
  ccall_nobox("w_wire_field_store_at", handle, 4, :d, d)
  ccall_nobox("w_wire_field_store_at", handle, 5, :temp, temp)
  handle

-> emit_wire_const_ipv4(f, a, b, c, cidr, d, temp)
  current_block(f)[:instructions].push(wire_make_const_ipv4(a, b, c, cidr, d, temp))

-> wire_make_const_ipv6(byte_len, cidr, string_id, temp, temp_ptr)
  handle = ccall_rawargs("w_wire_alloc", 70, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :byte_len, byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 1, :cidr, cidr)
  ccall_nobox("w_wire_field_store_at", handle, 2, :string_id, string_id)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp_ptr, temp_ptr)
  handle

-> emit_wire_const_ipv6(f, byte_len, cidr, string_id, temp, temp_ptr)
  current_block(f)[:instructions].push(wire_make_const_ipv6(byte_len, cidr, string_id, temp, temp_ptr))

-> wire_make_const_quantity(scale, sig, temp, unit_id)
  handle = ccall_rawargs("w_wire_alloc", 71, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :scale, scale)
  ccall_nobox("w_wire_field_store_at", handle, 1, :sig, sig)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :unit_id, unit_id)
  handle

-> emit_wire_const_quantity(f, scale, sig, temp, unit_id)
  current_block(f)[:instructions].push(wire_make_const_quantity(scale, sig, temp, unit_id))

-> wire_make_const_rational(den, num, temp)
  handle = ccall_rawargs("w_wire_alloc", 72, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :den, den)
  ccall_nobox("w_wire_field_store_at", handle, 1, :num, num)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_const_rational(f, den, num, temp)
  current_block(f)[:instructions].push(wire_make_const_rational(den, num, temp))

-> wire_make_const_uuid(byte_len, string_id, temp, temp_ptr)
  handle = ccall_rawargs("w_wire_alloc", 73, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :byte_len, byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 1, :string_id, string_id)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp_ptr, temp_ptr)
  handle

-> emit_wire_const_uuid(f, byte_len, string_id, temp, temp_ptr)
  current_block(f)[:instructions].push(wire_make_const_uuid(byte_len, string_id, temp, temp_ptr))

-> wire_make_fcmp_f64(lhs, pred, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 74, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :pred, pred)
  ccall_nobox("w_wire_field_store_at", handle, 2, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_fcmp_f64(f, lhs, pred, rhs, temp)
  current_block(f)[:instructions].push(wire_make_fcmp_f64(lhs, pred, rhs, temp))

-> wire_make_fma_f64(lhs, rhs, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 75, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :value, value)
  handle

-> emit_wire_fma_f64(f, lhs, rhs, temp, value)
  current_block(f)[:instructions].push(wire_make_fma_f64(lhs, rhs, temp, value))

-> wire_make_fmuladd_f64(lhs, rhs, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 76, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :value, value)
  handle

-> emit_wire_fmuladd_f64(f, lhs, rhs, temp, value)
  current_block(f)[:instructions].push(wire_make_fmuladd_f64(lhs, rhs, temp, value))

-> wire_make_ctpop_i64(value, temp)
  handle = ccall_rawargs("w_wire_alloc", 269, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :value, value)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_ctpop_i64(f, value, temp)
  current_block(f)[:instructions].push(wire_make_ctpop_i64(value, temp))

-> wire_make_fn_addr_i64(name, temp)
  handle = ccall_rawargs("w_wire_alloc", 77, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :name, name)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_fn_addr_i64(f, name, temp)
  current_block(f)[:instructions].push(wire_make_fn_addr_i64(name, temp))

-> wire_make_fneg_f64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 78, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_fneg_f64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_fneg_f64(temp, value))

-> wire_make_fpext_f16_f32(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 79, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_fpext_f16_f32(f, temp, value)
  current_block(f)[:instructions].push(wire_make_fpext_f16_f32(temp, value))

-> wire_make_fpext_f32_f64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 80, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_fpext_f32_f64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_fpext_f32_f64(temp, value))

-> wire_make_fptosi_f64_i64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 81, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_fptosi_f64_i64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_fptosi_f64_i64(temp, value))

-> wire_make_fptrunc_f32_f16(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 82, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_fptrunc_f32_f16(f, temp, value)
  current_block(f)[:instructions].push(wire_make_fptrunc_f32_f16(temp, value))

-> wire_make_fptrunc_f64_f32(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 83, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_fptrunc_f64_f32(f, temp, value)
  current_block(f)[:instructions].push(wire_make_fptrunc_f64_f32(temp, value))

-> wire_make_free_value(value)
  handle = ccall_rawargs("w_wire_alloc", 84, 1)
  ccall_nobox("w_wire_field_store_at", handle, 0, :value, value)
  handle

-> emit_wire_free_value(f, value)
  current_block(f)[:instructions].push(wire_make_free_value(value))

-> wire_make_gep_array(base, count, index, temp)
  handle = ccall_rawargs("w_wire_alloc", 85, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :base, base)
  ccall_nobox("w_wire_field_store_at", handle, 1, :count, count)
  ccall_nobox("w_wire_field_store_at", handle, 2, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_gep_array(f, base, count, index, temp)
  current_block(f)[:instructions].push(wire_make_gep_array(base, count, index, temp))

-> wire_make_i64_to_ptr(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 86, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_i64_to_ptr(f, temp, value)
  current_block(f)[:instructions].push(wire_make_i64_to_ptr(temp, value))

-> wire_make_icmp_eq_i32(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 87, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_icmp_eq_i32(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_icmp_eq_i32(lhs, rhs, temp))

-> wire_make_icmp_i64(lhs, pred, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 88, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :pred, pred)
  ccall_nobox("w_wire_field_store_at", handle, 2, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_icmp_i64(f, lhs, pred, rhs, temp)
  current_block(f)[:instructions].push(wire_make_icmp_i64(lhs, pred, rhs, temp))

-> wire_make_icmp_ne_i64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 89, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_icmp_ne_i64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_icmp_ne_i64(lhs, rhs, temp))

-> wire_make_icmp_ne_zero(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 90, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_icmp_ne_zero(f, temp, value)
  current_block(f)[:instructions].push(wire_make_icmp_ne_zero(temp, value))

-> wire_make_inttoptr_i64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 91, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_inttoptr_i64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_inttoptr_i64(temp, value))

-> wire_make_ivar_get(byte_len, self_reg, str_id, temp, temp_ptr)
  handle = ccall_rawargs("w_wire_alloc", 92, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :byte_len, byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 1, :self_reg, self_reg)
  ccall_nobox("w_wire_field_store_at", handle, 2, :str_id, str_id)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp_ptr, temp_ptr)
  handle

-> emit_wire_ivar_get(f, byte_len, self_reg, str_id, temp, temp_ptr)
  current_block(f)[:instructions].push(wire_make_ivar_get(byte_len, self_reg, str_id, temp, temp_ptr))

-> wire_make_ivar_get_idx(offset, self_reg, temp)
  handle = ccall_rawargs("w_wire_alloc", 93, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :offset, offset)
  ccall_nobox("w_wire_field_store_at", handle, 1, :self_reg, self_reg)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_ivar_get_idx(f, offset, self_reg, temp)
  current_block(f)[:instructions].push(wire_make_ivar_get_idx(offset, self_reg, temp))

-> wire_make_ivar_set(byte_len, self_reg, str_id, temp, temp_ptr, value)
  handle = ccall_rawargs("w_wire_alloc", 94, 6)
  ccall_nobox("w_wire_field_store_at", handle, 0, :byte_len, byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 1, :self_reg, self_reg)
  ccall_nobox("w_wire_field_store_at", handle, 2, :str_id, str_id)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp_ptr, temp_ptr)
  ccall_nobox("w_wire_field_store_at", handle, 5, :value, value)
  handle

-> emit_wire_ivar_set(f, byte_len, self_reg, str_id, temp, temp_ptr, value)
  current_block(f)[:instructions].push(wire_make_ivar_set(byte_len, self_reg, str_id, temp, temp_ptr, value))

-> wire_make_ivar_set_idx(offset, self_reg, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 95, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :offset, offset)
  ccall_nobox("w_wire_field_store_at", handle, 1, :self_reg, self_reg)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :value, value)
  handle

-> emit_wire_ivar_set_idx(f, offset, self_reg, temp, value)
  current_block(f)[:instructions].push(wire_make_ivar_set_idx(offset, self_reg, temp, value))

-> wire_make_load_class(class_name, temp)
  handle = ccall_rawargs("w_wire_alloc", 96, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :class_name, class_name)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_load_class(f, class_name, temp)
  current_block(f)[:instructions].push(wire_make_load_class(class_name, temp))

-> wire_make_load_cvar(cvar_key, temp)
  handle = ccall_rawargs("w_wire_alloc", 97, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :cvar_key, cvar_key)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_load_cvar(f, cvar_key, temp)
  current_block(f)[:instructions].push(wire_make_load_cvar(cvar_key, temp))

-> wire_make_load_global(name, temp, type)
  handle = ccall_rawargs("w_wire_alloc", 98, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :name, name)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :type, type)
  handle

-> emit_wire_load_global(f, name, temp, type)
  current_block(f)[:instructions].push(wire_make_load_global(name, temp, type))

-> wire_make_load_i64(ptr, temp)
  handle = ccall_rawargs("w_wire_alloc", 99, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_load_i64(f, ptr, temp)
  current_block(f)[:instructions].push(wire_make_load_i64(ptr, temp))

-> wire_make_load_i64_at(index, ptr, temp)
  handle = ccall_rawargs("w_wire_alloc", 100, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_load_i64_at(f, index, ptr, temp)
  current_block(f)[:instructions].push(wire_make_load_i64_at(index, ptr, temp))

-> wire_make_load_memo_ptr(global, temp)
  handle = ccall_rawargs("w_wire_alloc", 101, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :global, global)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_load_memo_ptr(f, global, temp)
  current_block(f)[:instructions].push(wire_make_load_memo_ptr(global, temp))

-> wire_make_load_ptr(ptr, temp)
  handle = ccall_rawargs("w_wire_alloc", 102, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_load_ptr(f, ptr, temp)
  current_block(f)[:instructions].push(wire_make_load_ptr(ptr, temp))

-> wire_make_load_u32_ptr(index, ptr, temp)
  handle = ccall_rawargs("w_wire_alloc", 103, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_load_u32_ptr(f, index, ptr, temp)
  current_block(f)[:instructions].push(wire_make_load_u32_ptr(index, ptr, temp))

-> wire_make_load_u64_ptr(index, ptr, temp)
  handle = ccall_rawargs("w_wire_alloc", 104, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_load_u64_ptr(f, index, ptr, temp)
  current_block(f)[:instructions].push(wire_make_load_u64_ptr(index, ptr, temp))

-> wire_make_load_u8_ptr(index, ptr, temp)
  handle = ccall_rawargs("w_wire_alloc", 105, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_load_u8_ptr(f, index, ptr, temp)
  current_block(f)[:instructions].push(wire_make_load_u8_ptr(index, ptr, temp))

-> wire_make_lshr_i128(shift, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 106, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :shift, shift)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :value, value)
  handle

-> emit_wire_lshr_i128(f, shift, temp, value)
  current_block(f)[:instructions].push(wire_make_lshr_i128(shift, temp, value))

-> wire_make_lshr_i64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 107, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_lshr_i64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_lshr_i64(lhs, rhs, temp))

-> wire_make_memo_call0_i64(fn_name, table, temp)
  handle = ccall_rawargs("w_wire_alloc", 108, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :fn_name, fn_name)
  ccall_nobox("w_wire_field_store_at", handle, 1, :table, table)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_memo_call0_i64(f, fn_name, table, temp)
  current_block(f)[:instructions].push(wire_make_memo_call0_i64(fn_name, table, temp))

-> wire_make_memo_call1_i64(args, fn_name, table, temp)
  handle = ccall_rawargs("w_wire_alloc", 109, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :args, wire_sequence(args))
  ccall_nobox("w_wire_field_store_at", handle, 1, :fn_name, fn_name)
  ccall_nobox("w_wire_field_store_at", handle, 2, :table, table)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_memo_call1_i64(f, args, fn_name, table, temp)
  current_block(f)[:instructions].push(wire_make_memo_call1_i64(args, fn_name, table, temp))

-> wire_make_memo_call2_i64(args, fn_name, table, temp)
  handle = ccall_rawargs("w_wire_alloc", 110, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :args, wire_sequence(args))
  ccall_nobox("w_wire_field_store_at", handle, 1, :fn_name, fn_name)
  ccall_nobox("w_wire_field_store_at", handle, 2, :table, table)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_memo_call2_i64(f, args, fn_name, table, temp)
  current_block(f)[:instructions].push(wire_make_memo_call2_i64(args, fn_name, table, temp))

-> wire_make_memo_init(temp)
  handle = ccall_rawargs("w_wire_alloc", 111, 1)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  handle

-> emit_wire_memo_init(f, temp)
  current_block(f)[:instructions].push(wire_make_memo_init(temp))

-> wire_make_mul_i128(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 112, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_mul_i128(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_mul_i128(lhs, rhs, temp))

-> wire_make_mulhi_u64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 113, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_mulhi_u64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_mulhi_u64(lhs, rhs, temp))

-> wire_make_nanbox_bool(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 114, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_nanbox_bool(f, temp, value)
  current_block(f)[:instructions].push(wire_make_nanbox_bool(temp, value))

-> wire_make_nanbox_float(raw, temp, temp_bits)
  handle = ccall_rawargs("w_wire_alloc", 115, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :raw, raw)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp_bits, temp_bits)
  handle

-> emit_wire_nanbox_float(f, raw, temp, temp_bits)
  current_block(f)[:instructions].push(wire_make_nanbox_float(raw, temp, temp_bits))

-> wire_make_nanbox_int(raw, temp, temp_masked)
  handle = ccall_rawargs("w_wire_alloc", 116, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :raw, raw)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp_masked, temp_masked)
  handle

-> emit_wire_nanbox_int(f, raw, temp, temp_masked)
  current_block(f)[:instructions].push(wire_make_nanbox_int(raw, temp, temp_masked))

-> wire_make_nanunbox_float(boxed, temp, temp_bits)
  handle = ccall_rawargs("w_wire_alloc", 117, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :boxed, boxed)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp_bits, temp_bits)
  handle

-> emit_wire_nanunbox_float(f, boxed, temp, temp_bits)
  current_block(f)[:instructions].push(wire_make_nanunbox_float(boxed, temp, temp_bits))

-> wire_make_nanunbox_int(boxed, temp, temp_shl)
  handle = ccall_rawargs("w_wire_alloc", 118, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :boxed, boxed)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp_shl, temp_shl)
  handle

-> emit_wire_nanunbox_int(f, boxed, temp, temp_shl)
  current_block(f)[:instructions].push(wire_make_nanunbox_int(boxed, temp, temp_shl))

-> wire_make_node_kind_class_register(class_temp, kind_id)
  handle = ccall_rawargs("w_wire_alloc", 119, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :class_temp, class_temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :kind_id, kind_id)
  handle

-> emit_wire_node_kind_class_register(f, class_temp, kind_id)
  current_block(f)[:instructions].push(wire_make_node_kind_class_register(class_temp, kind_id))

-> wire_make_not_i1(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 120, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_not_i1(f, temp, value)
  current_block(f)[:instructions].push(wire_make_not_i1(temp, value))

-> wire_make_null_ptr(temp)
  handle = ccall_rawargs("w_wire_alloc", 121, 1)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  handle

-> emit_wire_null_ptr(f, temp)
  current_block(f)[:instructions].push(wire_make_null_ptr(temp))

-> wire_make_or_i1(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 122, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_or_i1(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_or_i1(lhs, rhs, temp))

-> wire_make_phi_i64(a_label, a_value, b_label, b_value, temp)
  handle = ccall_rawargs("w_wire_alloc", 123, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :a_label, a_label)
  ccall_nobox("w_wire_field_store_at", handle, 1, :a_value, a_value)
  ccall_nobox("w_wire_field_store_at", handle, 2, :b_label, b_label)
  ccall_nobox("w_wire_field_store_at", handle, 3, :b_value, b_value)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp, temp)
  handle

-> emit_wire_phi_i64(f, a_label, a_value, b_label, b_value, temp)
  current_block(f)[:instructions].push(wire_make_phi_i64(a_label, a_value, b_label, b_value, temp))

-> wire_make_phi_ssa(incoming, temp)
  handle = ccall_rawargs("w_wire_alloc", 124, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :incoming, wire_sequence(incoming))
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_phi_ssa(f, incoming, temp)
  current_block(f)[:instructions].push(wire_make_phi_ssa(incoming, temp))

-> wire_make_poly_array_guard(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 125, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_poly_array_guard(f, temp, value)
  current_block(f)[:instructions].push(wire_make_poly_array_guard(temp, value))

-> wire_make_print_i64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 126, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_print_i64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_print_i64(temp, value))

-> wire_make_ptr_slot_get(index, ptr, slot_type, temp)
  handle = ccall_rawargs("w_wire_alloc", 127, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 2, :slot_type, slot_type)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_ptr_slot_get(f, index, ptr, slot_type, temp)
  current_block(f)[:instructions].push(wire_make_ptr_slot_get(index, ptr, slot_type, temp))

-> wire_make_ptr_to_i64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 128, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_ptr_to_i64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_ptr_to_i64(temp, value))

-> wire_make_puts_i64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 129, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_puts_i64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_puts_i64(temp, value))

-> wire_make_register_unit(byte_len, str_id, unit_id)
  handle = ccall_rawargs("w_wire_alloc", 130, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :byte_len, byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 1, :str_id, str_id)
  ccall_nobox("w_wire_field_store_at", handle, 2, :unit_id, unit_id)
  handle

-> emit_wire_register_unit(f, byte_len, str_id, unit_id)
  current_block(f)[:instructions].push(wire_make_register_unit(byte_len, str_id, unit_id))

-> wire_make_ret_i32(value)
  handle = ccall_rawargs("w_wire_alloc", 131, 1)
  ccall_nobox("w_wire_field_store_at", handle, 0, :value, value)
  handle

-> emit_wire_ret_i32(f, value)
  current_block(f)[:instructions].push(wire_make_ret_i32(value))

-> wire_make_ret_i64(function_recycle_count, value)
  handle = ccall_rawargs("w_wire_alloc", 132, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :function_recycle_count, function_recycle_count)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_ret_i64(f, function_recycle_count, value)
  current_block(f)[:instructions].push(wire_make_ret_i64(function_recycle_count, value))

-> wire_make_ret_void()
  handle = ccall_rawargs("w_wire_alloc", 133, 0)
  handle

-> emit_wire_ret_void(f)
  current_block(f)[:instructions].push(wire_make_ret_void())

-> wire_make_sadd_with_overflow(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 134, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_sadd_with_overflow(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_sadd_with_overflow(lhs, rhs, temp))

-> wire_make_scope_pop(id)
  handle = ccall_rawargs("w_wire_alloc", 135, 1)
  ccall_nobox("w_wire_field_store_at", handle, 0, :id, id)
  handle

-> emit_wire_scope_pop(f, id)
  current_block(f)[:instructions].push(wire_make_scope_pop(id))

-> wire_make_scope_push(id)
  handle = ccall_rawargs("w_wire_alloc", 136, 1)
  ccall_nobox("w_wire_field_store_at", handle, 0, :id, id)
  handle

-> emit_wire_scope_push(f, id)
  current_block(f)[:instructions].push(wire_make_scope_push(id))

-> wire_make_sdiv_i64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 137, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_sdiv_i64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_sdiv_i64(lhs, rhs, temp))

-> wire_make_select_i64(cond, else_val, temp, then_val)
  handle = ccall_rawargs("w_wire_alloc", 138, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :cond, cond)
  ccall_nobox("w_wire_field_store_at", handle, 1, :else_val, else_val)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :then_val, then_val)
  handle

-> emit_wire_select_i64(f, cond, else_val, temp, then_val)
  current_block(f)[:instructions].push(wire_make_select_i64(cond, else_val, temp, then_val))

-> wire_make_setjmp(buf, temp)
  handle = ccall_rawargs("w_wire_alloc", 139, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :buf, buf)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_setjmp(f, buf, temp)
  current_block(f)[:instructions].push(wire_make_setjmp(buf, temp))

-> wire_make_shl_i64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 140, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_shl_i64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_shl_i64(lhs, rhs, temp))

-> wire_make_slab_alloc_init(fields, kind, sc, temp)
  handle = ccall_rawargs("w_wire_alloc", 141, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :fields, wire_sequence(fields))
  ccall_nobox("w_wire_field_store_at", handle, 1, :kind, kind)
  ccall_nobox("w_wire_field_store_at", handle, 2, :sc, sc)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_slab_alloc_init(f, fields, kind, sc, temp)
  current_block(f)[:instructions].push(wire_make_slab_alloc_init(fields, kind, sc, temp))

-> wire_make_small_array_alloca(temp_ptr, total_bytes)
  handle = ccall_rawargs("w_wire_alloc", 142, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp_ptr, temp_ptr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :total_bytes, total_bytes)
  handle

-> emit_wire_small_array_alloca(f, temp_ptr, total_bytes)
  current_block(f)[:instructions].push(wire_make_small_array_alloca(temp_ptr, total_bytes))

-> wire_make_small_array_const_load(const_name, temp)
  handle = ccall_rawargs("w_wire_alloc", 143, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :const_name, const_name)
  ccall_nobox("w_wire_field_store_at", handle, 1, :temp, temp)
  handle

-> emit_wire_small_array_const_load(f, const_name, temp)
  current_block(f)[:instructions].push(wire_make_small_array_const_load(const_name, temp))

-> wire_make_small_array_get_inline(arr, bits, headerless, idx, idx_raw, s, signed, temp)
  handle = ccall_rawargs("w_wire_alloc", 144, 8)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arr, arr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :bits, bits)
  ccall_nobox("w_wire_field_store_at", handle, 2, :headerless, headerless)
  ccall_nobox("w_wire_field_store_at", handle, 3, :idx, idx)
  ccall_nobox("w_wire_field_store_at", handle, 4, :idx_raw, idx_raw)
  ccall_nobox("w_wire_field_store_at", handle, 5, :s, wire_sequence(s))
  ccall_nobox("w_wire_field_store_at", handle, 6, :signed, signed)
  ccall_nobox("w_wire_field_store_at", handle, 7, :temp, temp)
  handle

-> emit_wire_small_array_get_inline(f, arr, bits, headerless, idx, idx_raw, s, signed, temp)
  current_block(f)[:instructions].push(wire_make_small_array_get_inline(arr, bits, headerless, idx, idx_raw, s, signed, temp))

-> wire_make_small_array_set_inline(arr, bits, headerless, idx, idx_raw, s, signed, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 145, 9)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arr, arr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :bits, bits)
  ccall_nobox("w_wire_field_store_at", handle, 2, :headerless, headerless)
  ccall_nobox("w_wire_field_store_at", handle, 3, :idx, idx)
  ccall_nobox("w_wire_field_store_at", handle, 4, :idx_raw, idx_raw)
  ccall_nobox("w_wire_field_store_at", handle, 5, :s, wire_sequence(s))
  ccall_nobox("w_wire_field_store_at", handle, 6, :signed, signed)
  ccall_nobox("w_wire_field_store_at", handle, 7, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 8, :value, value)
  handle

-> emit_wire_small_array_set_inline(f, arr, bits, headerless, idx, idx_raw, s, signed, temp, value)
  current_block(f)[:instructions].push(wire_make_small_array_set_inline(arr, bits, headerless, idx, idx_raw, s, signed, temp, value))

-> wire_make_store_cvar(cvar_key, value)
  handle = ccall_rawargs("w_wire_alloc", 146, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :cvar_key, cvar_key)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_store_cvar(f, cvar_key, value)
  current_block(f)[:instructions].push(wire_make_store_cvar(cvar_key, value))

-> wire_make_store_double(ptr, value)
  handle = ccall_rawargs("w_wire_alloc", 147, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_store_double(f, ptr, value)
  current_block(f)[:instructions].push(wire_make_store_double(ptr, value))

-> wire_make_store_float(ptr, value)
  handle = ccall_rawargs("w_wire_alloc", 148, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_store_float(f, ptr, value)
  current_block(f)[:instructions].push(wire_make_store_float(ptr, value))

-> wire_make_store_global(name, type, value)
  handle = ccall_rawargs("w_wire_alloc", 149, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :name, name)
  ccall_nobox("w_wire_field_store_at", handle, 1, :type, type)
  ccall_nobox("w_wire_field_store_at", handle, 2, :value, value)
  handle

-> emit_wire_store_global(f, name, type, value)
  current_block(f)[:instructions].push(wire_make_store_global(name, type, value))

-> wire_make_store_i64(ptr, value)
  handle = ccall_rawargs("w_wire_alloc", 150, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_store_i64(f, ptr, value)
  current_block(f)[:instructions].push(wire_make_store_i64(ptr, value))

-> wire_make_store_memo_ptr(global, value)
  handle = ccall_rawargs("w_wire_alloc", 151, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :global, global)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_store_memo_ptr(f, global, value)
  current_block(f)[:instructions].push(wire_make_store_memo_ptr(global, value))

-> wire_make_store_ptr(dest, value)
  handle = ccall_rawargs("w_wire_alloc", 152, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :dest, dest)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_store_ptr(f, dest, value)
  current_block(f)[:instructions].push(wire_make_store_ptr(dest, value))

-> wire_make_store_u8_ptr(index, ptr, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 153, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :value, value)
  handle

-> emit_wire_store_u8_ptr(f, index, ptr, temp, value)
  current_block(f)[:instructions].push(wire_make_store_u8_ptr(index, ptr, temp, value))

-> wire_make_string_i64(byte_len, string_id, temp, temp_ptr)
  handle = ccall_rawargs("w_wire_alloc", 154, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :byte_len, byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 1, :string_id, string_id)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp_ptr, temp_ptr)
  handle

-> emit_wire_string_i64(f, byte_len, string_id, temp, temp_ptr)
  current_block(f)[:instructions].push(wire_make_string_i64(byte_len, string_id, temp, temp_ptr))

-> wire_make_sub_i64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 155, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_sub_i64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_sub_i64(lhs, rhs, temp))

-> wire_make_subborrow_u64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 156, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_subborrow_u64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_subborrow_u64(lhs, rhs, temp))

-> wire_make_switch_i64(cases, default_label, is_symbol, value)
  handle = ccall_rawargs("w_wire_alloc", 157, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :cases, wire_sequence(cases))
  ccall_nobox("w_wire_field_store_at", handle, 1, :default_label, default_label)
  ccall_nobox("w_wire_field_store_at", handle, 2, :is_symbol, is_symbol)
  ccall_nobox("w_wire_field_store_at", handle, 3, :value, value)
  handle

-> emit_wire_switch_i64(f, cases, default_label, is_symbol, value)
  current_block(f)[:instructions].push(wire_make_switch_i64(cases, default_label, is_symbol, value))

-> wire_make_symbol_i64(byte_len, string_id, temp, temp_ptr)
  handle = ccall_rawargs("w_wire_alloc", 158, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :byte_len, byte_len)
  ccall_nobox("w_wire_field_store_at", handle, 1, :string_id, string_id)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp_ptr, temp_ptr)
  handle

-> emit_wire_symbol_i64(f, byte_len, string_id, temp, temp_ptr)
  current_block(f)[:instructions].push(wire_make_symbol_i64(byte_len, string_id, temp, temp_ptr))

-> wire_make_ta_cap_raw(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 159, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_ta_cap_raw(f, temp, value)
  current_block(f)[:instructions].push(wire_make_ta_cap_raw(temp, value))

-> wire_make_ta_data_addr(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 160, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_ta_data_addr(f, temp, value)
  current_block(f)[:instructions].push(wire_make_ta_data_addr(temp, value))

-> wire_make_ta_size_raw(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 161, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_ta_size_raw(f, temp, value)
  current_block(f)[:instructions].push(wire_make_ta_size_raw(temp, value))

-> wire_make_trunc_i128_i64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 162, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_trunc_i128_i64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_trunc_i128_i64(temp, value))

-> wire_make_trunc_i64_i16(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 163, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_trunc_i64_i16(f, temp, value)
  current_block(f)[:instructions].push(wire_make_trunc_i64_i16(temp, value))

-> wire_make_trunc_i64_i32(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 164, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_trunc_i64_i32(f, temp, value)
  current_block(f)[:instructions].push(wire_make_trunc_i64_i32(temp, value))

-> wire_make_truthy_inline(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 165, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_truthy_inline(f, temp, value)
  current_block(f)[:instructions].push(wire_make_truthy_inline(temp, value))

-> wire_make_type_class_register(class_temp, dispatch_key)
  handle = ccall_rawargs("w_wire_alloc", 166, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :class_temp, class_temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :dispatch_key, dispatch_key)
  handle

-> emit_wire_type_class_register(f, class_temp, dispatch_key)
  current_block(f)[:instructions].push(wire_make_type_class_register(class_temp, dispatch_key))

-> wire_make_typed_array_compound_op_inline(arr, bits, compound_op, idx, idx_raw, s, signed, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 167, 9)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arr, arr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :bits, bits)
  ccall_nobox("w_wire_field_store_at", handle, 2, :compound_op, compound_op)
  ccall_nobox("w_wire_field_store_at", handle, 3, :idx, idx)
  ccall_nobox("w_wire_field_store_at", handle, 4, :idx_raw, idx_raw)
  ccall_nobox("w_wire_field_store_at", handle, 5, :s, wire_sequence(s))
  ccall_nobox("w_wire_field_store_at", handle, 6, :signed, signed)
  ccall_nobox("w_wire_field_store_at", handle, 7, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 8, :value, value)
  handle

-> emit_wire_typed_array_compound_op_inline(f, arr, bits, compound_op, idx, idx_raw, s, signed, temp, value)
  current_block(f)[:instructions].push(wire_make_typed_array_compound_op_inline(arr, bits, compound_op, idx, idx_raw, s, signed, temp, value))

-> wire_make_typed_array_get_inline(arr, bits, idx, idx_raw, s, signed, temp)
  handle = ccall_rawargs("w_wire_alloc", 168, 7)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arr, arr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :bits, bits)
  ccall_nobox("w_wire_field_store_at", handle, 2, :idx, idx)
  ccall_nobox("w_wire_field_store_at", handle, 3, :idx_raw, idx_raw)
  ccall_nobox("w_wire_field_store_at", handle, 4, :s, wire_sequence(s))
  ccall_nobox("w_wire_field_store_at", handle, 5, :signed, signed)
  ccall_nobox("w_wire_field_store_at", handle, 6, :temp, temp)
  handle

-> emit_wire_typed_array_get_inline(f, arr, bits, idx, idx_raw, s, signed, temp)
  current_block(f)[:instructions].push(wire_make_typed_array_get_inline(arr, bits, idx, idx_raw, s, signed, temp))

-> wire_make_typed_array_set_inline(arr, bits, idx, idx_raw, s, signed, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 169, 8)
  ccall_nobox("w_wire_field_store_at", handle, 0, :arr, arr)
  ccall_nobox("w_wire_field_store_at", handle, 1, :bits, bits)
  ccall_nobox("w_wire_field_store_at", handle, 2, :idx, idx)
  ccall_nobox("w_wire_field_store_at", handle, 3, :idx_raw, idx_raw)
  ccall_nobox("w_wire_field_store_at", handle, 4, :s, wire_sequence(s))
  ccall_nobox("w_wire_field_store_at", handle, 5, :signed, signed)
  ccall_nobox("w_wire_field_store_at", handle, 6, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 7, :value, value)
  handle

-> emit_wire_typed_array_set_inline(f, arr, bits, idx, idx_raw, s, signed, temp, value)
  current_block(f)[:instructions].push(wire_make_typed_array_set_inline(arr, bits, idx, idx_raw, s, signed, temp, value))

-> wire_make_unreachable()
  handle = ccall_rawargs("w_wire_alloc", 170, 0)
  handle

-> emit_wire_unreachable(f)
  current_block(f)[:instructions].push(wire_make_unreachable())

-> wire_make_view_base_ptr(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 171, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_view_base_ptr(f, temp, value)
  current_block(f)[:instructions].push(wire_make_view_base_ptr(temp, value))

-> wire_make_view_load_bit(index, ptr, temp)
  handle = ccall_rawargs("w_wire_alloc", 172, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_view_load_bit(f, index, ptr, temp)
  current_block(f)[:instructions].push(wire_make_view_load_bit(index, ptr, temp))

-> wire_make_view_load_byte(index, ptr, temp)
  handle = ccall_rawargs("w_wire_alloc", 173, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 1, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_view_load_byte(f, index, ptr, temp)
  current_block(f)[:instructions].push(wire_make_view_load_byte(index, ptr, temp))

-> wire_make_view_load_field(field_type, offset, ptr, size, temp)
  handle = ccall_rawargs("w_wire_alloc", 174, 5)
  ccall_nobox("w_wire_field_store_at", handle, 0, :field_type, field_type)
  ccall_nobox("w_wire_field_store_at", handle, 1, :offset, offset)
  ccall_nobox("w_wire_field_store_at", handle, 2, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 3, :size, size)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp, temp)
  handle

-> emit_wire_view_load_field(f, field_type, offset, ptr, size, temp)
  current_block(f)[:instructions].push(wire_make_view_load_field(field_type, offset, ptr, size, temp))

-> wire_make_view_load_inline_byte(index, offset, ptr, temp)
  handle = ccall_rawargs("w_wire_alloc", 175, 4)
  ccall_nobox("w_wire_field_store_at", handle, 0, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 1, :offset, offset)
  ccall_nobox("w_wire_field_store_at", handle, 2, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 3, :temp, temp)
  handle

-> emit_wire_view_load_inline_byte(f, index, offset, ptr, temp)
  current_block(f)[:instructions].push(wire_make_view_load_inline_byte(index, offset, ptr, temp))

-> wire_make_view_load_inline_elem(elem, index, offset, ptr, size, temp)
  handle = ccall_rawargs("w_wire_alloc", 176, 6)
  ccall_nobox("w_wire_field_store_at", handle, 0, :elem, elem)
  ccall_nobox("w_wire_field_store_at", handle, 1, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 2, :offset, offset)
  ccall_nobox("w_wire_field_store_at", handle, 3, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 4, :size, size)
  ccall_nobox("w_wire_field_store_at", handle, 5, :temp, temp)
  handle

-> emit_wire_view_load_inline_elem(f, elem, index, offset, ptr, size, temp)
  current_block(f)[:instructions].push(wire_make_view_load_inline_elem(elem, index, offset, ptr, size, temp))

-> wire_make_view_store_field(field_type, offset, ptr, size, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 177, 6)
  ccall_nobox("w_wire_field_store_at", handle, 0, :field_type, field_type)
  ccall_nobox("w_wire_field_store_at", handle, 1, :offset, offset)
  ccall_nobox("w_wire_field_store_at", handle, 2, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 3, :size, size)
  ccall_nobox("w_wire_field_store_at", handle, 4, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 5, :value, value)
  handle

-> emit_wire_view_store_field(f, field_type, offset, ptr, size, temp, value)
  current_block(f)[:instructions].push(wire_make_view_store_field(field_type, offset, ptr, size, temp, value))

-> wire_make_view_store_inline_elem(elem, index, offset, ptr, size, temp, value)
  handle = ccall_rawargs("w_wire_alloc", 178, 7)
  ccall_nobox("w_wire_field_store_at", handle, 0, :elem, elem)
  ccall_nobox("w_wire_field_store_at", handle, 1, :index, index)
  ccall_nobox("w_wire_field_store_at", handle, 2, :offset, offset)
  ccall_nobox("w_wire_field_store_at", handle, 3, :ptr, ptr)
  ccall_nobox("w_wire_field_store_at", handle, 4, :size, size)
  ccall_nobox("w_wire_field_store_at", handle, 5, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 6, :value, value)
  handle

-> emit_wire_view_store_inline_elem(f, elem, index, offset, ptr, size, temp, value)
  current_block(f)[:instructions].push(wire_make_view_store_inline_elem(elem, index, offset, ptr, size, temp, value))

-> wire_make_xor_i64(lhs, rhs, temp)
  handle = ccall_rawargs("w_wire_alloc", 179, 3)
  ccall_nobox("w_wire_field_store_at", handle, 0, :lhs, lhs)
  ccall_nobox("w_wire_field_store_at", handle, 1, :rhs, rhs)
  ccall_nobox("w_wire_field_store_at", handle, 2, :temp, temp)
  handle

-> emit_wire_xor_i64(f, lhs, rhs, temp)
  current_block(f)[:instructions].push(wire_make_xor_i64(lhs, rhs, temp))

-> wire_make_zext_i16_i64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 180, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_zext_i16_i64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_zext_i16_i64(temp, value))

-> wire_make_zext_i32_i64(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 181, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_zext_i32_i64(f, temp, value)
  current_block(f)[:instructions].push(wire_make_zext_i32_i64(temp, value))

-> wire_make_zext_i64_i128(temp, value)
  handle = ccall_rawargs("w_wire_alloc", 182, 2)
  ccall_nobox("w_wire_field_store_at", handle, 0, :temp, temp)
  ccall_nobox("w_wire_field_store_at", handle, 1, :value, value)
  handle

-> emit_wire_zext_i64_i128(f, temp, value)
  current_block(f)[:instructions].push(wire_make_zext_i64_i128(temp, value))

-> wire_make_dynamic_0(op)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 0)
  handle

-> emit_wire_dynamic_0(f, op)
  current_block(f)[:instructions].push(wire_make_dynamic_0(op))

-> wire_make_dynamic_1(op, field0, value0)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 1)
  if wire_sequence_field?(field0)
    value0 = wire_sequence(value0)
  ccall_nobox("w_wire_field_store_at", handle, 0, field0, value0)
  handle

-> emit_wire_dynamic_1(f, op, field0, value0)
  current_block(f)[:instructions].push(wire_make_dynamic_1(op, field0, value0))

-> wire_make_dynamic_2(op, field0, value0, field1, value1)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 2)
  if wire_sequence_field?(field0)
    value0 = wire_sequence(value0)
  ccall_nobox("w_wire_field_store_at", handle, 0, field0, value0)
  if wire_sequence_field?(field1)
    value1 = wire_sequence(value1)
  ccall_nobox("w_wire_field_store_at", handle, 1, field1, value1)
  handle

-> emit_wire_dynamic_2(f, op, field0, value0, field1, value1)
  current_block(f)[:instructions].push(wire_make_dynamic_2(op, field0, value0, field1, value1))

-> wire_make_dynamic_3(op, field0, value0, field1, value1, field2, value2)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 3)
  if wire_sequence_field?(field0)
    value0 = wire_sequence(value0)
  ccall_nobox("w_wire_field_store_at", handle, 0, field0, value0)
  if wire_sequence_field?(field1)
    value1 = wire_sequence(value1)
  ccall_nobox("w_wire_field_store_at", handle, 1, field1, value1)
  if wire_sequence_field?(field2)
    value2 = wire_sequence(value2)
  ccall_nobox("w_wire_field_store_at", handle, 2, field2, value2)
  handle

-> emit_wire_dynamic_3(f, op, field0, value0, field1, value1, field2, value2)
  current_block(f)[:instructions].push(wire_make_dynamic_3(op, field0, value0, field1, value1, field2, value2))

-> wire_make_dynamic_4(op, field0, value0, field1, value1, field2, value2, field3, value3)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 4)
  if wire_sequence_field?(field0)
    value0 = wire_sequence(value0)
  ccall_nobox("w_wire_field_store_at", handle, 0, field0, value0)
  if wire_sequence_field?(field1)
    value1 = wire_sequence(value1)
  ccall_nobox("w_wire_field_store_at", handle, 1, field1, value1)
  if wire_sequence_field?(field2)
    value2 = wire_sequence(value2)
  ccall_nobox("w_wire_field_store_at", handle, 2, field2, value2)
  if wire_sequence_field?(field3)
    value3 = wire_sequence(value3)
  ccall_nobox("w_wire_field_store_at", handle, 3, field3, value3)
  handle

-> emit_wire_dynamic_4(f, op, field0, value0, field1, value1, field2, value2, field3, value3)
  current_block(f)[:instructions].push(wire_make_dynamic_4(op, field0, value0, field1, value1, field2, value2, field3, value3))

-> wire_make_dynamic_5(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 5)
  if wire_sequence_field?(field0)
    value0 = wire_sequence(value0)
  ccall_nobox("w_wire_field_store_at", handle, 0, field0, value0)
  if wire_sequence_field?(field1)
    value1 = wire_sequence(value1)
  ccall_nobox("w_wire_field_store_at", handle, 1, field1, value1)
  if wire_sequence_field?(field2)
    value2 = wire_sequence(value2)
  ccall_nobox("w_wire_field_store_at", handle, 2, field2, value2)
  if wire_sequence_field?(field3)
    value3 = wire_sequence(value3)
  ccall_nobox("w_wire_field_store_at", handle, 3, field3, value3)
  if wire_sequence_field?(field4)
    value4 = wire_sequence(value4)
  ccall_nobox("w_wire_field_store_at", handle, 4, field4, value4)
  handle

-> emit_wire_dynamic_5(f, op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4)
  current_block(f)[:instructions].push(wire_make_dynamic_5(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4))

-> wire_make_dynamic_6(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 6)
  if wire_sequence_field?(field0)
    value0 = wire_sequence(value0)
  ccall_nobox("w_wire_field_store_at", handle, 0, field0, value0)
  if wire_sequence_field?(field1)
    value1 = wire_sequence(value1)
  ccall_nobox("w_wire_field_store_at", handle, 1, field1, value1)
  if wire_sequence_field?(field2)
    value2 = wire_sequence(value2)
  ccall_nobox("w_wire_field_store_at", handle, 2, field2, value2)
  if wire_sequence_field?(field3)
    value3 = wire_sequence(value3)
  ccall_nobox("w_wire_field_store_at", handle, 3, field3, value3)
  if wire_sequence_field?(field4)
    value4 = wire_sequence(value4)
  ccall_nobox("w_wire_field_store_at", handle, 4, field4, value4)
  if wire_sequence_field?(field5)
    value5 = wire_sequence(value5)
  ccall_nobox("w_wire_field_store_at", handle, 5, field5, value5)
  handle

-> emit_wire_dynamic_6(f, op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5)
  current_block(f)[:instructions].push(wire_make_dynamic_6(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5))

-> wire_make_dynamic_7(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 7)
  if wire_sequence_field?(field0)
    value0 = wire_sequence(value0)
  ccall_nobox("w_wire_field_store_at", handle, 0, field0, value0)
  if wire_sequence_field?(field1)
    value1 = wire_sequence(value1)
  ccall_nobox("w_wire_field_store_at", handle, 1, field1, value1)
  if wire_sequence_field?(field2)
    value2 = wire_sequence(value2)
  ccall_nobox("w_wire_field_store_at", handle, 2, field2, value2)
  if wire_sequence_field?(field3)
    value3 = wire_sequence(value3)
  ccall_nobox("w_wire_field_store_at", handle, 3, field3, value3)
  if wire_sequence_field?(field4)
    value4 = wire_sequence(value4)
  ccall_nobox("w_wire_field_store_at", handle, 4, field4, value4)
  if wire_sequence_field?(field5)
    value5 = wire_sequence(value5)
  ccall_nobox("w_wire_field_store_at", handle, 5, field5, value5)
  if wire_sequence_field?(field6)
    value6 = wire_sequence(value6)
  ccall_nobox("w_wire_field_store_at", handle, 6, field6, value6)
  handle

-> emit_wire_dynamic_7(f, op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6)
  current_block(f)[:instructions].push(wire_make_dynamic_7(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6))

-> wire_make_dynamic_8(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6, field7, value7)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 8)
  if wire_sequence_field?(field0)
    value0 = wire_sequence(value0)
  ccall_nobox("w_wire_field_store_at", handle, 0, field0, value0)
  if wire_sequence_field?(field1)
    value1 = wire_sequence(value1)
  ccall_nobox("w_wire_field_store_at", handle, 1, field1, value1)
  if wire_sequence_field?(field2)
    value2 = wire_sequence(value2)
  ccall_nobox("w_wire_field_store_at", handle, 2, field2, value2)
  if wire_sequence_field?(field3)
    value3 = wire_sequence(value3)
  ccall_nobox("w_wire_field_store_at", handle, 3, field3, value3)
  if wire_sequence_field?(field4)
    value4 = wire_sequence(value4)
  ccall_nobox("w_wire_field_store_at", handle, 4, field4, value4)
  if wire_sequence_field?(field5)
    value5 = wire_sequence(value5)
  ccall_nobox("w_wire_field_store_at", handle, 5, field5, value5)
  if wire_sequence_field?(field6)
    value6 = wire_sequence(value6)
  ccall_nobox("w_wire_field_store_at", handle, 6, field6, value6)
  if wire_sequence_field?(field7)
    value7 = wire_sequence(value7)
  ccall_nobox("w_wire_field_store_at", handle, 7, field7, value7)
  handle

-> emit_wire_dynamic_8(f, op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6, field7, value7)
  current_block(f)[:instructions].push(wire_make_dynamic_8(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6, field7, value7))

-> wire_make_dynamic_9(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6, field7, value7, field8, value8)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 9)
  if wire_sequence_field?(field0)
    value0 = wire_sequence(value0)
  ccall_nobox("w_wire_field_store_at", handle, 0, field0, value0)
  if wire_sequence_field?(field1)
    value1 = wire_sequence(value1)
  ccall_nobox("w_wire_field_store_at", handle, 1, field1, value1)
  if wire_sequence_field?(field2)
    value2 = wire_sequence(value2)
  ccall_nobox("w_wire_field_store_at", handle, 2, field2, value2)
  if wire_sequence_field?(field3)
    value3 = wire_sequence(value3)
  ccall_nobox("w_wire_field_store_at", handle, 3, field3, value3)
  if wire_sequence_field?(field4)
    value4 = wire_sequence(value4)
  ccall_nobox("w_wire_field_store_at", handle, 4, field4, value4)
  if wire_sequence_field?(field5)
    value5 = wire_sequence(value5)
  ccall_nobox("w_wire_field_store_at", handle, 5, field5, value5)
  if wire_sequence_field?(field6)
    value6 = wire_sequence(value6)
  ccall_nobox("w_wire_field_store_at", handle, 6, field6, value6)
  if wire_sequence_field?(field7)
    value7 = wire_sequence(value7)
  ccall_nobox("w_wire_field_store_at", handle, 7, field7, value7)
  if wire_sequence_field?(field8)
    value8 = wire_sequence(value8)
  ccall_nobox("w_wire_field_store_at", handle, 8, field8, value8)
  handle

-> emit_wire_dynamic_9(f, op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6, field7, value7, field8, value8)
  current_block(f)[:instructions].push(wire_make_dynamic_9(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6, field7, value7, field8, value8))

-> wire_make_dynamic_10(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6, field7, value7, field8, value8, field9, value9)
  kind_id = ccall_nobox("w_numeric_to_i64", wire_kind_id(op))
  handle = ccall_rawargs("w_wire_alloc", kind_id, 10)
  if wire_sequence_field?(field0)
    value0 = wire_sequence(value0)
  ccall_nobox("w_wire_field_store_at", handle, 0, field0, value0)
  if wire_sequence_field?(field1)
    value1 = wire_sequence(value1)
  ccall_nobox("w_wire_field_store_at", handle, 1, field1, value1)
  if wire_sequence_field?(field2)
    value2 = wire_sequence(value2)
  ccall_nobox("w_wire_field_store_at", handle, 2, field2, value2)
  if wire_sequence_field?(field3)
    value3 = wire_sequence(value3)
  ccall_nobox("w_wire_field_store_at", handle, 3, field3, value3)
  if wire_sequence_field?(field4)
    value4 = wire_sequence(value4)
  ccall_nobox("w_wire_field_store_at", handle, 4, field4, value4)
  if wire_sequence_field?(field5)
    value5 = wire_sequence(value5)
  ccall_nobox("w_wire_field_store_at", handle, 5, field5, value5)
  if wire_sequence_field?(field6)
    value6 = wire_sequence(value6)
  ccall_nobox("w_wire_field_store_at", handle, 6, field6, value6)
  if wire_sequence_field?(field7)
    value7 = wire_sequence(value7)
  ccall_nobox("w_wire_field_store_at", handle, 7, field7, value7)
  if wire_sequence_field?(field8)
    value8 = wire_sequence(value8)
  ccall_nobox("w_wire_field_store_at", handle, 8, field8, value8)
  if wire_sequence_field?(field9)
    value9 = wire_sequence(value9)
  ccall_nobox("w_wire_field_store_at", handle, 9, field9, value9)
  handle

-> emit_wire_dynamic_10(f, op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6, field7, value7, field8, value8, field9, value9)
  current_block(f)[:instructions].push(wire_make_dynamic_10(op, field0, value0, field1, value1, field2, value2, field3, value3, field4, value4, field5, value5, field6, value6, field7, value7, field8, value8, field9, value9))
