use ../lib/metaflip/rect/portfolio

-> ffrdst_expect(label, condition)
  if !condition
    << "FAIL " + label
    exit(1)
  1

# Apply a simultaneous cyclic permutation to the two index sets carried by a
# rectangular factor mask.  Using the same n/m/p permutations on U/V/W is an
# exact matrix-multiplication-tensor isotropy.
-> ffrdst_cycle_factor(mask, rows, columns) (i64 i64 i64) i64
  result = 0 ## i64
  row = 0 ## i64
  while row < rows
    column = 0 ## i64
    while column < columns
      if ((mask >> (row * columns + column)) & 1) == 1
        next_row = (row + 1) % rows ## i64
        next_column = (column + 1) % columns ## i64
        result = result | (1 << (next_row * columns + next_column))
      column += 1
    row += 1
  result

-> ffrdst_cycle_scheme(src, n, m, p, capacity, seed) (i64[] i64 i64 i64 i64 i64)
  rank = ffr_best_rank(src) ## i64
  us = i64[capacity]
  vs = i64[capacity]
  ws = i64[capacity]
  i = 0 ## i64
  while i < rank
    us[i] = ffrdst_cycle_factor(src[src[47] + i], n, m)
    vs[i] = ffrdst_cycle_factor(src[src[48] + i], m, p)
    ws[i] = ffrdst_cycle_factor(src[src[49] + i], n, p)
    i += 1
  dst = i64[ffr_state_size(capacity)]
  loaded = ffr_init_terms_cap(dst, us, vs, ws, rank, n, m, p, capacity, seed, 4, 4, 1000, 500) ## i64
  if loaded != rank || ffr_verify_best_exact(dst, n, m, p) != 1
    return nil
  dst

root = __DIR__ + "/../lib/metaflip/seeds/gf2/"

# 2x2x9: three raw term sets generated by cyclic/reverse p-index actions are
# one structural basin even though their numeric masks differ.
n = 2 ## i64
m = 2 ## i64
p = 9 ## i64
capacity = ffr_default_capacity(n, m, p) ## i64
p9a = i64[ffr_state_size(capacity)]
p9b = i64[ffr_state_size(capacity)]
p9c = i64[ffr_state_size(capacity)]
r9a = ffr_load_scheme_cap(p9a, root + "matmul_2x2x9_rank32_d156_perminov_2025_gf2.txt", n, m, p, capacity, 99101, 4, 4, 1000, 500) ## i64
r9b = ffr_load_scheme_cap(p9b, root + "matmul_2x2x9_rank32_d156_perminov_2025_pperm_cycle_gf2.txt", n, m, p, capacity, 99102, 4, 4, 1000, 500) ## i64
r9c = ffr_load_scheme_cap(p9c, root + "matmul_2x2x9_rank32_d156_perminov_2025_pperm_reverse_gf2.txt", n, m, p, capacity, 99103, 4, 4, 1000, 500) ## i64
z = ffrdst_expect("2x2x9 doors exact and distinct", r9a == 32 && r9b == 32 && r9c == 32 && ffrda_same_best(p9a, p9b) == 0 && ffrda_same_best(p9a, p9c) == 0)
s9a = ffrda_structural_signature(p9a) ## i64
z = ffrdst_expect("2x2x9 coordinate copies collapse", s9a == ffrda_structural_signature(p9b) && s9a == ffrda_structural_signature(p9c))

# The 3x4x6 and 2x5x6 catalogue/frontier pairs are support-disjoint GL/orbit
# images.  Raw symmetric difference calls them maximally far apart; the new
# signature correctly recognizes that this is not a second structural basin.
n = 3
m = 4
p = 6
capacity = ffr_default_capacity(n, m, p)
p346a = i64[ffr_state_size(capacity)]
p346b = i64[ffr_state_size(capacity)]
r346a = ffr_load_scheme_cap(p346a, root + "matmul_3x4x6_rank54_catalog_gf2.txt", n, m, p, capacity, 99201, 4, 4, 1000, 500) ## i64
r346b = ffr_load_scheme_cap(p346b, root + "matmul_3x4x6_rank54_d488_gl_frontier_gf2.txt", n, m, p, capacity, 99202, 4, 4, 1000, 500) ## i64
z = ffrdst_expect("3x4x6 GL doors exact and support-disjoint", r346a == 54 && r346b == 54 && ffrda_best_distance(p346a, p346b) == 108)
z = ffrdst_expect("3x4x6 GL copies collapse", ffrda_structural_signature(p346a) == ffrda_structural_signature(p346b))

n = 2
m = 5
p = 6
capacity = ffr_default_capacity(n, m, p)
p256a = i64[ffr_state_size(capacity)]
p256b = i64[ffr_state_size(capacity)]
r256a = ffr_load_scheme_cap(p256a, root + "matmul_2x5x6_rank47_catalog_gf2.txt", n, m, p, capacity, 99301, 4, 4, 1000, 500) ## i64
r256b = ffr_load_scheme_cap(p256b, root + "matmul_2x5x6_rank47_d438_orbit_door_gf2.txt", n, m, p, capacity, 99302, 4, 4, 1000, 500) ## i64
z = ffrdst_expect("2x5x6 orbit doors exact and support-disjoint", r256a == 47 && r256b == 47 && ffrda_best_distance(p256a, p256b) == 94)
z = ffrdst_expect("2x5x6 orbit copies collapse", ffrda_structural_signature(p256a) == ffrda_structural_signature(p256b))

# 4x6x7 has two genuinely different exact rank-123 families.  A fresh cyclic
# image of the leader must collapse, while the catalogue family must remain a
# novel structural choice.  Capacity-one selection proves that novelty wins;
# the one-candidate arm proves the distance fallback still fills the slot.
n = 4
m = 6
p = 7
capacity = ffr_default_capacity(n, m, p)
p467leader = i64[ffr_state_size(capacity)]
p467other = i64[ffr_state_size(capacity)]
r467leader = ffr_load_scheme_cap(p467leader, root + "matmul_4x6x7_rank123_d1406_gl_frontier_gf2.txt", n, m, p, capacity, 99401, 4, 4, 1000, 500) ## i64
r467other = ffr_load_scheme_cap(p467other, root + "matmul_4x6x7_rank123_catalog_gf2.txt", n, m, p, capacity, 99402, 4, 4, 1000, 500) ## i64
p467copy = ffrdst_cycle_scheme(p467leader, n, m, p, capacity, 99403)
z = ffrdst_expect("4x6x7 families and cyclic image exact", r467leader == 123 && r467other == 123 && p467copy != nil && ffr_verify_best_exact(p467copy, n, m, p) == 1)
leader_signature = ffrda_structural_signature(p467leader) ## i64
z = ffrdst_expect("4x6x7 cyclic image collapses", ffrda_same_best(p467leader, p467copy) == 0 && leader_signature == ffrda_structural_signature(p467copy))
z = ffrdst_expect("4x6x7 distinct family remains distinct", leader_signature != ffrda_structural_signature(p467other))

pool = []
pool.push(p467copy)
pool.push(p467other)
selected = []
selected_count = ffrda_select_diverse(pool, p467leader, 1, selected) ## i64
z = ffrdst_expect("selector prefers novel 4x6x7 family", selected_count == 1 && ffrda_same_best(selected[0], p467other) == 1)

reverse_pool = []
reverse_pool.push(p467other)
reverse_pool.push(p467copy)
reverse_selected = []
reverse_count = ffrda_select_diverse(reverse_pool, p467leader, 1, reverse_selected) ## i64
z = ffrdst_expect("structural preference is arrival-order independent", reverse_count == 1 && ffrda_same_best(reverse_selected[0], selected[0]) == 1)

fallback_pool = []
fallback_pool.push(p467copy)
fallback_selected = []
fallback_count = ffrda_select_diverse(fallback_pool, p467leader, 1, fallback_selected) ## i64
z = ffrdst_expect("structural collision falls back instead of rejecting", fallback_count == 1 && ffrda_same_best(fallback_selected[0], p467copy) == 1)

# Repeat the largest signature enough times to keep its exit-only cost visible
# in routine test logs.  No timing threshold is asserted across machines.
iterations = 200 ## i64
checksum = 0 ## i64
t0 = ccall("__w_clock_ms") ## i64
i = 0 ## i64
while i < iterations
  checksum = (checksum + ffrda_structural_signature(p467leader) + ffrda_structural_signature(p467other) + i) & 9223372036854775807
  i += 1
elapsed_ms = ccall("__w_clock_ms") - t0 ## i64
signature_us = elapsed_ms * 1000 / (iterations * 2) ## i64

<< "PASS rectangular structural side-door selection signatures=" + s9a.to_s() + "/" + leader_signature.to_s() + " d467=" + ffrda_best_distance(p467leader, p467other).to_s() + " signature_us=" + signature_us.to_s() + " checksum=" + checksum.to_s()
