#!/usr/bin/env python3
"""Generate the LEXCHAR classification table for fast lexer character dispatch.

Outputs a 128-entry lookup table where each byte encodes classification bits:
  bit 0: digit (0-9)
  bit 1: lower (a-z)
  bit 2: upper (A-Z)
  bit 3: hex (0-9, a-f, A-F)
  bit 4: ident_start (a-z, _)
  bit 5: ident_char (a-z, 0-9, _)
  bit 6: name_char (a-z, A-Z, 0-9, _)
  bit 7: whitespace (space, tab)
"""

DIGIT = 0x01
LOWER = 0x02
UPPER = 0x04
HEX   = 0x08
IDENT_START = 0x10
IDENT_CHAR  = 0x20
NAME_CHAR   = 0x40
WHITESPACE  = 0x80

table = [0] * 128

for cp in range(128):
    c = chr(cp)
    v = 0
    if c.isdigit():
        v |= DIGIT | HEX | IDENT_CHAR | NAME_CHAR
    if c.islower():
        v |= LOWER | IDENT_START | IDENT_CHAR | NAME_CHAR
    if c.isupper():
        v |= UPPER | NAME_CHAR
    if c in 'abcdefABCDEF':
        v |= HEX
    if c == '_':
        v |= IDENT_START | IDENT_CHAR | NAME_CHAR
    if c in ' \t':
        v |= WHITESPACE
    table[cp] = v

# Output as Tungsten array literal
print("# LexChar classification table — auto-generated by scripts/gen_lexchar_table.py")
print("# bit 0=digit 1=lower 2=upper 3=hex 4=ident_start 5=ident_char 6=name_char 7=whitespace")
print("LEXCHAR = [")
for i in range(0, 128, 16):
    row = ", ".join(str(table[j]) for j in range(i, min(i+16, 128)))
    label = f"  # {i:3d}-{min(i+15,127):3d}"
    if i == 0: label += " (control)"
    elif i == 32: label += " (space ! \" # ...)"
    elif i == 48: label += " (0-9 : ; < = > ?)"
    elif i == 64: label += " (@ A-O)"
    elif i == 80: label += " (P-Z [ \\ ] ^ _)"
    elif i == 96: label += " (` a-o)"
    elif i == 112: label += " (p-z { | } ~)"
    print(f"  {row},{label}")
print("]")

# Also output as C array
print()
print("/* C version */")
print("static const uint8_t w_lexchar_table[128] = {")
for i in range(0, 128, 16):
    row = ", ".join(f"0x{table[j]:02x}" for j in range(i, min(i+16, 128)))
    print(f"    {row},")
print("};")
