#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate doc/CORE.md from the standard-library autoload manifest.
#
# The manifest in core/tungsten.w (`auto :Name, "path"`) is the single source of
# truth for which stdlib classes/traits exist. This walks it, reads each
# core/<path>.w for its declaration line and leading doc comment, and emits a
# grouped reference table. Run via `rake doc:core` (or directly).
#
# CORE.md is GENERATED — do not hand-edit; change the source files' header
# comments or the manifest instead, then regenerate.

ROOT = File.expand_path("..", __dir__)
MANIFEST = File.join(ROOT, "core", "tungsten.w")
OUT = File.join(ROOT, "doc", "CORE.md")

# Pull `auto :Name, "path"` entries from the manifest, in declaration order.
entries = File.readlines(MANIFEST).filter_map do |line|
  m = line.match(/^\s*auto\s+:(\w+),\s*"([^"]+)"/)
  m && { name: m[1], path: m[2] }
end

abort "no auto entries found in #{MANIFEST}" if entries.empty?

# Extract the declaration line (`+ Name...` / `trait Name`) and a one-line
# summary (first substantive leading comment) from a core source file.
def describe(file, name)
  return ["", "—"] unless File.exist?(file)

  decl = nil
  comments = []
  saw_code = false
  File.foreach(file) do |raw|
    line = raw.rstrip
    next if line.empty? && !saw_code && comments.empty?
    if line.lstrip.start_with?("#") && !saw_code
      comments << line.lstrip.sub(/\A(#+\s*)+/, "") # strip nested '# # ' headers too
      next
    end
    if (m = line.match(/^\s*(\+\s+\S.*|trait\s+\S.*)$/))
      decl = m[1].strip
      saw_code = true
      break
    end
    # First non-comment, non-decl code line — stop collecting the header block.
    break unless line.empty?
  end

  # A line is a usable summary unless it's metadata, a URL, an ASCII-art tree
  # line, or just the class name repeated as a header.
  summary = comments.find do |c|
    s = c.strip
    !s.empty? &&
      !s.start_with?("@") &&            # @resources / metadata
      !s.match?(%r{\Ahttps?://}) &&     # bare URLs
      !s.match?(/\A[└├│─|]/) &&         # ASCII-art tree lines
      s.casecmp(name) != 0 &&           # bare "ClassName" header
      s.casecmp("#{name} trait") != 0   # "Foo trait" header
  end
  summary = summary.to_s.strip
  summary = "#{summary[0, 117]}…" if summary.length > 118
  [decl.to_s, summary.empty? ? "—" : summary]
end

def section_for(path)
  return "Traits" if path.start_with?("traits/")
  return "Numeric tower" if path.start_with?("numeric/")
  "Core classes"
end

rows = entries.map do |e|
  decl, summary = describe(File.join(ROOT, "core", "#{e[:path]}.w"), e[:name])
  e.merge(decl: decl, summary: summary, section: section_for(e[:path]))
end

order = ["Core classes", "Numeric tower", "Traits"]
out = +<<~HEADER
  # Tungsten Core Library

  <!-- GENERATED by scripts/gen_core_doc.rb — do not edit by hand.
       Regenerate with `rake doc:core` after changing core/tungsten.w or a
       class's header comment. -->

  The standard library is lazily autoloaded from the `auto :Name, "path"` table
  in [`core/tungsten.w`](../core/tungsten.w): a class is invisible until it is
  registered there. This reference lists every registered class and trait
  (#{rows.size} total), grouped by area, with its declaration, a one-line
  summary from the source header, and a link to the source.

HEADER

order.each do |sec|
  group = rows.select { |r| r[:section] == sec }
  next if group.empty?

  out << "\n## #{sec}\n\n"
  out << "| Class | Defined as | Summary | Source |\n"
  out << "|-------|-----------|---------|--------|\n"
  group.each do |r|
    decl = r[:decl].empty? ? "—" : "`#{r[:decl]}`"
    src = "[`core/#{r[:path]}.w`](../core/#{r[:path]}.w)"
    summary = r[:summary].gsub("|", "\\|")
    out << "| `#{r[:name]}` | #{decl} | #{summary} | #{src} |\n"
  end
end

if ARGV.include?("--check")
  current = File.exist?(OUT) ? File.read(OUT) : ""
  if current == out
    puts "doc/CORE.md is up to date (#{rows.size} classes/traits)"
  else
    warn "doc/CORE.md is STALE — regenerate with `rake doc:core` (ruby scripts/gen_core_doc.rb)"
    exit 1
  end
else
  File.write(OUT, out)
  puts "wrote #{OUT} (#{rows.size} classes/traits)"
end
