# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}" }

# Specify your gem's dependencies in tungsten.gemspec
gemspec

gem "bigdecimal"
gem "uuidtools"

gem "irb",                   require: false
gem "reline",                require: false
gem "ostruct",               require: false
gem "tty-markdown",          require: false

gem "rake", "~> 13.0",       require: false

gem "rubocop", "~> 1.21",    require: false
gem "rubocop-rake",          require: false
gem "rubocop-rails-omakase", require: false
gem "rubocop-rspec",         require: false

group :test do
  gem "rspec", require: false
end

# To investigate
# gem 'ruby-llvm' '>= 3.5.0'

gem "stackprof", "~> 0.2.28", group: :development
