# frozen_string_literal: true

begin
  require 'rubygems'
  require 'bundler/setup'
rescue LoadError
  puts "You must `gem install bundler` and `bundle install` to run rake tasks."
end

require "bundler/gem_tasks"

desc "Copy shared unit registry inputs into the standalone Ruby gem"
task :prepare_unit_registry do
  require "fileutils"
  root = File.expand_path("../..", __dir__)
  %w[unit_registry.json unit_metadata.tsv substance_densities.json].each do |name|
    FileUtils.mkdir_p(File.join(__dir__, "data"))
    FileUtils.cp(File.join(root, "data", name), File.join(__dir__, "data", name))
  end
  FileUtils.cp(File.join(root, "scripts/lib/unit_registry.rb"),
               File.join(__dir__, "lib/tungsten/generated_unit_registry.rb"))
end
Rake::Task["build"].enhance([:prepare_unit_registry])

require "rubocop/rake_task"
RuboCop::RakeTask.new

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(:spec) do |task|
  task.exclude_pattern = "spec/parity_spec.rb"
end

RSpec::Core::RakeTask.new(:expensive) do |task|
  task.pattern = "spec/**/*_expensive.rb"
  task.rspec_opts = "-f failures"
end

RSpec::Core::RakeTask.new(:parity) do |task|
  task.pattern = "spec/parity_spec.rb"
end

desc "Launch a console with Tungsten loaded"
task :console do
  ARGV.clear

  require "tungsten"
  require "pry"

  Pry.start
end

task default: :spec # %i[rubocop spec]
