# Modular (evaluation/interpolation) multivariate GCD over finite fields.
# Reopens Polynomial; load after polynomial_gcd.w.
#
# Brown's dense modular algorithm: the polynomials are viewed in one main
# variable over the ring generated by the others; one of those coefficient
# variables is evaluated at distinct field points, the image GCDs are computed
# recursively, scaled by the evaluated GCD of the leading coefficients so they
# agree with one fixed polynomial, and interpolated back with Newton steps.
# Unlucky points are detected by degree jumps, the result is verified by trial
# division, and small fields or a failed verification fall back to the exact
# primitive polynomial-remainder sequence in polynomial_gcd.w.

+ Polynomial
  # Dense coefficient array in one variable of a polynomial that involves
  # only that variable.
  -> dense_coefficients_in(index)
    out = []
    limit = degree_in(index)
    i = 0
    while i <= limit
      out.push(@ring.field.zero)
      i += 1
    @terms.each -> (term)
      out[term[1][index]] = term[0]
    out

  -> polynomial_from_dense_in(values, index)
    terms = []
    i = 0
    while i < values.size
      if !field_zero?(values[i])
        powers = @ring.zero_exponents
        powers[index] = i
        terms.push([values[i], powers])
      i += 1
    Polynomial.new(@ring, terms)

  # Euclid on dense coefficient arrays for two polynomials in one active
  # variable; returns the monic GCD.
  -> dense_gcd_in(other, index)
    left = dense_element_trim(dense_coefficients_in(index))
    right = dense_element_trim(other.dense_coefficients_in(index))
    while right.size > 0
      remainder = dense_element_remainder(left, right)
      left = right
      right = remainder
    return @ring.zero if left.size == 0
    polynomial_from_dense_in(left, index).monic

  # Variables (indices) that appear in either polynomial.
  -> active_variables_with(other)
    out = []
    i = 0
    while i < @ring.arity
      if degree_in(i) > 0 || other.degree_in(i) > 0
        out.push(i)
      i += 1
    out

  # GCD of the coefficients in `main` (polynomials in the other variables).
  -> modular_content_in(main)
    result = @ring.zero
    exponent = 0
    limit = degree_in(main)
    while exponent <= limit
      coefficient = coefficient_in(main, exponent)
      if !coefficient.zero?
        result = result.zero? ? coefficient.monic : result.modular_gcd(coefficient)
        return @ring.one if result.constant?
      exponent += 1
    result

  # Modular GCD; monic, same contract as `gcd`.
  -> modular_gcd(other)
    other = coerce(other)
    return other.monic if zero?
    return monic if other.zero?
    active = active_variables_with(other)
    return @ring.one if active.size == 0
    if active.size == 1
      return dense_gcd_in(other, active[0])
    raise "modular gcd requires a finite coefficient field" if !@ring.field.finite_field?
    result = modular_gcd_active(other, active)
    result.class_name == "Nil" ? gcd_recursive(other, highest_active_variable(other)) : result

  # Returns nil when the field runs out of evaluation points or verification
  # fails, so the caller can fall back to the exact remainder sequence.
  -> modular_gcd_active(other, active)
    main = active[active.size - 1]
    evaluated = active[0]
    left_content = modular_content_in(main)
    right_content = other.modular_content_in(main)
    common_content = left_content.modular_gcd(right_content)
    left = left_content.constant? ? monic : (self / left_content).monic
    right = right_content.constant? ? other.monic : (other / right_content).monic
    left_lc = left.coefficient_in(main, left.degree_in(main))
    right_lc = right.coefficient_in(main, right.degree_in(main))
    gamma = left_lc.modular_gcd(right_lc)
    left_eval_degree = left.degree_in(evaluated)
    right_eval_degree = right.degree_in(evaluated)
    minimum_eval_degree = left_eval_degree < right_eval_degree ? left_eval_degree : right_eval_degree
    bound = gamma.degree_in(evaluated) + minimum_eval_degree
    field = @ring.field
    return nil if field.order <= bound + 1

    interpolant = @ring.zero
    node_product = @ring.one
    nodes = []
    image_degree = -1
    point = 0
    while point < field.order
      value = field.element_from_index(point)
      point += 1
      next if field.zero?(left_lc.substitute_element(evaluated, value).leading_coefficient)
      next if field.zero?(right_lc.substitute_element(evaluated, value).leading_coefficient)
      left_image = left.substitute_element(evaluated, value)
      right_image = right.substitute_element(evaluated, value)
      image_gcd = left_image.modular_gcd(right_image)
      image_main_degree = image_gcd.degree_in(main)
      return common_content.monic if image_main_degree == 0
      if image_degree >= 0 && image_main_degree > image_degree
        next
      if image_degree < 0 || image_main_degree < image_degree
        image_degree = image_main_degree
        interpolant = @ring.zero
        node_product = @ring.one
        nodes = []
      scaled = image_gcd * gamma.substitute_element(evaluated, value)
      difference = scaled - interpolant.substitute_element(evaluated, value)
      if !difference.zero?
        denominator = field.one
        nodes.each -> (node)
          denominator = field.multiply(denominator, field.subtract(value, node))
        scale = field.divide(field.one, denominator)
        correction = node_product.monomial_multiply_raw(@ring.zero_exponents, scale) * difference
        interpolant = interpolant + correction
      powers = @ring.zero_exponents
      powers[evaluated] = 1
      node_factor = @ring.monomial_raw(field.one, powers) - @ring.constant(value)
      node_product = node_product * node_factor
      nodes.push(value)
      if nodes.size > bound
        candidate = interpolant
        candidate_content = candidate.modular_content_in(main)
        if !candidate_content.constant?
          candidate = candidate / candidate_content
        candidate = candidate.monic
        if left.divmod(candidate)[1].zero? && right.divmod(candidate)[1].zero?
          return (common_content * candidate).monic
        return nil
    nil

  -> gcd(other)
    other = coerce(other)
    if @ring.field.finite_field? && @ring.arity >= 2
      return modular_gcd(other)
    gcd_recursive(other, highest_active_variable(other))
