# Finite symmetry groups acting on a lattice by integer matrices.
#
# A lattice's point group is generated by a couple of matrices — a rotation
# and a reflection — and everything else follows by composition. This class
# takes generators and closes them into the full group, so callers describe a
# lattice by its generators rather than spelling out every element.
#
# The crystallographic restriction says a plane lattice can only have 2-, 3-,
# 4- or 6-fold rotational symmetry, so in two dimensions there are exactly two
# interesting cases, and both are here: the square lattice with D4 of order 8,
# and the triangular/hexagonal lattice with D6 of order 12. In three
# dimensions the cube has 24 rotations, or 48 once reflections are allowed.

+ LatticeSymmetry
  -> new(elements)
    @elements = elements
    @dimension = elements[0].size

  -> elements
    @elements

  -> order
    @elements.size

  -> dimension
    @dimension

  -> .multiply(a, b)
    n = a.size
    out = []
    i = 0
    while i < n
      row = []
      j = 0
      while j < n
        total = 0
        k = 0
        while k < n
          total += a[i][k] * b[k][j]
          k += 1
        row.push(total)
        j += 1
      out.push(row)
      i += 1
    out

  -> .apply(m, v)
    n = m.size
    out = []
    i = 0
    while i < n
      total = 0
      j = 0
      while j < n
        total += m[i][j] * v[j]
        j += 1
      out.push(total)
      i += 1
    out

  -> .identity(n)
    out = []
    i = 0
    while i < n
      row = []
      j = 0
      while j < n
        row.push(i == j ? 1 : 0)
        j += 1
      out.push(row)
      i += 1
    out

  -> .matrix_key(m)
    parts = []
    i = 0
    while i < m.size
      j = 0
      while j < m[i].size
        parts.push("[m[i][j]]")
        j += 1
      i += 1
    parts.join(",")

  # Close a set of generators under multiplication. The group is finite for
  # any lattice point group, so the breadth-first product search terminates.
  -> .closure(generators)
    n = generators[0].size
    seen = {}
    elements = []
    identity = LatticeSymmetry.identity(n)
    seen[LatticeSymmetry.matrix_key(identity)] = true
    elements.push(identity)
    head = 0
    while head < elements.size
      current = elements[head]
      head += 1
      g = 0
      while g < generators.size
        product = LatticeSymmetry.multiply(current, generators[g])
        key = LatticeSymmetry.matrix_key(product)
        if !seen.key?(key)
          seen[key] = true
          elements.push(product)
        g += 1
      raise "symmetry group did not close (over 10000 elements)" if elements.size > 10000
    LatticeSymmetry.new(elements)

  # D4, order 8: quarter turn plus a mirror.
  -> .square
    LatticeSymmetry.closure([[[0, 0 - 1], [1, 0]], [[0 - 1, 0], [0, 1]]])

  # D6, order 12, in axial coordinates for the triangular lattice. A sixty
  # degree turn sends (q, r) to (-r, q + r).
  -> .hexagonal
    LatticeSymmetry.closure([[[0, 0 - 1], [1, 1]], [[0, 1], [1, 0]]])

  # The 24 rotations of the cube: quarter turns about two axes generate them.
  -> .cubic_rotations
    LatticeSymmetry.closure([
      [[0, 0 - 1, 0], [1, 0, 0], [0, 0, 1]],
      [[1, 0, 0], [0, 0, 0 - 1], [0, 1, 0]]])

  # The full 48-element group, rotations together with reflections.
  -> .cubic
    LatticeSymmetry.closure([
      [[0, 0 - 1, 0], [1, 0, 0], [0, 0, 1]],
      [[1, 0, 0], [0, 0, 0 - 1], [0, 1, 0]],
      [[0 - 1, 0, 0], [0, 1, 0], [0, 0, 1]]])

  # Rotations only: those of determinant +1.
  -> rotations
    out = []
    @elements.each ->(m)
      out.push(m) if LatticeSymmetry.determinant(m) == 1
    LatticeSymmetry.new(out)

  -> .determinant(m)
    n = m.size
    return m[0][0] if n == 1
    return m[0][0] * m[1][1] - m[0][1] * m[1][0] if n == 2
    total = 0
    j = 0
    while j < n
      minor = []
      i = 1
      while i < n
        row = []
        k = 0
        while k < n
          row.push(m[i][k]) if k != j
          k += 1
        minor.push(row)
        i += 1
      term = m[0][j] * LatticeSymmetry.determinant(minor)
      total += (j % 2 == 0) ? term : 0 - term
      j += 1
    total
